### ISSUE TITLE
[Feature request]whitelist

### ISSUE THREAD

**Issue by lelemka0** [Dr-TSNG/Hide-My-Applist#10]
Hope to add features to implement that selected applications are only allowed to access specific applications.
For example, allowing qq to access applications that use quick login, because qq needs to use the getPackageInfo method to verify signatures. Except for apps that need quick login, selecting all apps is inconvenient.

**Comment by byxiaorun** [comment]
🕊️🕊️🕊️This is in the plan. pls wait patiently.🕊️🕊️🕊️

**Comment by Dr-TSNG** [comment]
White list added
