### ISSUE TITLE
Issue with last Magisk Canary

### ISSUE THREAD

**Issue by xerta555** [Dr-TSNG/Hide-My-Applist#106]
Hi

I recently tried the new Magisk Canary version (with Zygisk), in this version as you know MagiskHide no more exist.

I use the app of my bank wich have few root detections methods, i have tried to hide everything to this app, but it still detect root.

Is it due to the fact that there are some issues with some features of this app or due to some detections methods with are not supported by HMA ?

The bancking app: https://play.google.com/store/apps/details?id=com.cm_prod.bad

Thanks in advance.

**Comment by Dr-TSNG** [comment]
If u uninstall magisk app it still fails, do NOT report here since we only hide applist.

**Comment by xerta555** [comment]
> 
> 
> since we only hide applist.

But HMA provide support for a few applist detections methods

**Comment by Dr-TSNG** [comment]
I say if you uninstall the magisk app it still fails, then it has nothing to do with HMA because we only hide applist, not root.

**Comment by xerta555** [comment]
> 
> 
> I say if you uninstall the magisk app it still fails, then it has nothing to do with HMA because we only hide applist, not root.

Ah ok sorry i didn't understand in that sense.
