### ISSUE TITLE
建议增加自动将检测出的应用加入隐藏

### ISSUE THREAD

**Issue by RC1844** [Dr-TSNG/Hide-My-Applist#107]
rt，应用列表检测器可以检测出来这些应用，那就可以一键将这些应用加入隐藏列表里，这样方便不少。直接让检测器导出模板也是可以的。

**Comment by Howard20181** [comment]
你用白名单算了，虽然说不推荐的

**Comment by RC1844** [comment]
> 你用白名单算了，虽然说不推荐的

白名单也不好使啊，要加系统应用列表

**Comment by Dr-TSNG** [comment]
乱七八糟
