### ISSUE TITLE
我用这软件来实现隐藏桌面图标，让系统桌面彻底检测不到一些软件

### ISSUE THREAD

**Issue by youling257** [Dr-TSNG/Hide-My-Applist#108]
我这样设置达不到我的目标

**Comment by youling257** [comment]
![Screenshot_2021-11-07-12-08-26-36_6b8d254452bc4a3798e188525542e357](https://user-images.githubusercontent.com/16304724/140632010-aec0760c-a342-4924-b284-46d60428cdb3.jpg)
![Screenshot_2021-11-07-12-08-34-27_6b8d254452bc4a3798e188525542e357](https://user-images.githubusercontent.com/16304724/140632025-a736af3c-85cc-43e3-bb5e-4d58775fe36a.jpg)
![Screenshot_2021-11-07-12-08-49-70_6b8d254452bc4a3798e188525542e357](https://user-images.githubusercontent.com/16304724/140632032-2e1e2b8d-805a-44e2-ae81-af70d8161d31.jpg)
![Screenshot_2021-11-07-12-09-10-01_6b8d254452bc4a3798e188525542e357](https://user-images.githubusercontent.com/16304724/140632046-438a2d87-ec1a-49ee-b030-2fddcab1b50b.jpg)
![Screenshot_2021-11-07-12-10-05-83_084ab3bc34f7aa7ccff83653f52abafc](https://user-images.githubusercontent.com/16304724/140632050-477c628e-f213-4e38-85ef-f095125b9bb2.jpg)

**Comment by cracky5322** [comment]
沒辦法自訂隱藏應用的啟動器可以丟了
