### ISSUE TITLE
对google play商店隐藏某个应用，让其检测不到更新

### ISSUE THREAD

**Issue by youling257** [Dr-TSNG/Hide-My-Applist#109]
这软件能做到吗

**Comment by youling257** [comment]
![Screenshot_2021-11-07-12-15-37-74_084ab3bc34f7aa7ccff83653f52abafc](https://user-images.githubusercontent.com/16304724/140632152-81e0a31f-57ba-4a23-ba70-d99704c95b4c.jpg)
![Screenshot_2021-11-07-12-16-01-92_6b8d254452bc4a3798e188525542e357](https://user-images.githubusercontent.com/16304724/140632161-aa63c98d-0d06-4624-856e-9226f959bb4f.jpg)
![Screenshot_2021-11-07-12-16-05-32_6b8d254452bc4a3798e188525542e357](https://user-images.githubusercontent.com/16304724/140632166-4a0665a5-3ec2-4c84-89fb-b212ab642841.jpg)
![Screenshot_2021-11-07-12-16-22-92_6b8d254452bc4a3798e188525542e357](https://user-images.githubusercontent.com/16304724/140632173-0f890887-7532-42ba-bc88-8fb56d5fac20.jpg)

我这样设置还是达不到我的目的

**Comment by Dr-TSNG** [comment]
@youling257 你连关于里的帮助都没读过就来这里提问，压根就用不来这软件，我只能认为你是在 spam
