### ISSUE TITLE
[Feature]Per-App Block Selection instead of Only Using Template

### ISSUE THREAD

**Issue by huajijam** [Dr-TSNG/Hide-My-Applist#11]
Using template with per-app customize instead of just using template.
Only using template to config might cause some app need to re-create an nearly same config tamplate but with a small change

**Comment by huajijam** [comment]
zh_CN
用模板与app单独配置混合的配置方式(且对app的单独配置优先级高于模板)替换现阶段只能选择模板的方式
只使用模板来配置将导致一些app需要重新做一个几乎一模一样的模板(例如只变了一两个app)，这并不usr friendly

**Comment by Dr-TSNG** [comment]
Completed
