### ISSUE TITLE
[问题]检测测试检测到自身为Xposed moudles爆红

### ISSUE THREAD

**Issue by SaLTNEko** [Dr-TSNG/Hide-My-Applist#110]
![微信图片_20211008101221](https://user-images.githubusercontent.com/30261880/141296709-d5e8db7c-b3b7-4dc5-9251-33d7218cf7f2.jpg)

**Comment by cracky5322** [comment]
@SaLTNEko 你會隔離其他模塊不會隔離 HMA 嗎？

**Comment by SaLTNEko** [comment]
设置所有需要root的app为模板，并正确设置应用app，但是银行app依旧可以检测到使用magisk+手机被root

**Comment by cracky5322** [comment]
@SaLTNEko 這是隱藏應用列表，不是隱藏 ROOT，你要不要重新搞清楚這個有用是在幹什麼的？

**Comment by SaLTNEko** [comment]
对检测测试设置隔离HMA的意义在哪里呢...模块里面HMA 检测测试 已经隐藏项目的magisk都已经添加了 但是还是会被检测到magisk

**Comment by cracky5322** [comment]
@SaLTNEko 是檢測你所安裝的「應用」不是檢測你所刷入的 ROOT，你是哪里搞錯了嗎

**Comment by SaLTNEko** [comment]
我只是描述程序的情况而已...magisk也被检测到了啊

**Comment by SaLTNEko** [comment]
因为看描述说检测测试通过再设置模块 所以才问最后一个爆红要怎么隔离

**Comment by cracky5322** [comment]
@SaLTNEko 銀行檢測應用列表或是其他東西 HMA 僅負責應用列表，不負責其他項目

**Comment by cracky5322** [comment]
@SaLTNEko 看是什麼項目檢測了就把他隔離掉啊...
你是什麼被檢測也不說，怎麼設定的也不截圖，隔空抓藥？還是要包郵 50 到我手裡幫你看？

**Comment by SaLTNEko** [comment]
检测截图我已经发送了 爆红的就是HMA自带的检测测试 设置在这里 之前不放是因为看了很多教程确定设置是没有问题的 发现不能隐藏 排错发现检测测试比别人的多一排爆红不知道怎么解决来问一下 
![1](https://user-images.githubusercontent.com/30261880/141299731-25c71c97-ef8b-4a87-8947-07b2b8b3cb40.jpg)
![2](https://user-images.githubusercontent.com/30261880/141299734-6686a0ef-8817-4960-94a0-1ebea5d06b29.jpg)
![3](https://user-images.githubusercontent.com/30261880/141299739-eaadb27d-35a9-448c-a2d0-6a2651d91773.jpg)
![4](https://user-images.githubusercontent.com/30261880/141299742-21a0b586-d363-4a57-a235-1e075277495a.jpg)

**Comment by cracky5322** [comment]
@SaLTNEko 爆紅也來張圖看看

**Comment by cracky5322** [comment]
@SaLTNEko 你說爆紅該不會是顯示隱藏應用列表吧
你有沒有把隱藏應用列表加到名單內

**Comment by SaLTNEko** [comment]
![5](https://user-images.githubusercontent.com/30261880/141300290-7a11deb7-b1ac-44a6-8544-c227684af211.jpg)
我的问题是 我设置了隐藏magisk 其他需要root的程序也添加在模块里面了 但是以及被检测到手机安装了magisk 想问一下是不是因为MHA作为xposed插件被检测到的原因

**Comment by SaLTNEko** [comment]
加了 第一张图我的模块设置就是添加 以及settings就是我magisk隐藏程序名的名字

**Comment by cracky5322** [comment]
@SaLTNEko 對應用列表檢測器啟用黑名單了對吧

**Comment by SaLTNEko** [comment]
是的 启用的是黑名单 我没有设置白名单模板 如果选错根本不会有对应模板设置

**Comment by cracky5322** [comment]
@SaLTNEko 設定完成後是否有儲存，儲存後是否有強制停止檢測器

**Comment by SaLTNEko** [comment]
存储了 我选择了设置里的终止系统服务 重新启动后在LSPosed里重新开启了MHA （只选择了系统框架）依旧会被检测到 更糟糕的是我现在对应的app卡在了开屏界面 是我的操作存在问题吗 这是对应的日志信息 因为都是同样的报错所以以拍照的方式发送了 感谢您的回复
![10](https://user-images.githubusercontent.com/30261880/141303510-7ff4fc07-279f-4808-9572-aa90c634aa34.jpg)

![6](https://user-images.githubusercontent.com/30261880/141302520-82962f6f-cc13-4a1f-a126-f0b75e10b11c.jpg)
![8](https://user-images.githubusercontent.com/30261880/141302536-70738fe9-042d-4bc3-a876-6b38ae659da6.jpg)
![7](https://user-images.githubusercontent.com/30261880/141302673-6205f11c-b1d7-4bfc-9633-99ccbad78d3a.jpg)

**Comment by cracky5322** [comment]
@SaLTNEko 你的檢測器版本過舊請更新
https://t.me/HideMyApplist/99

同時順便檢查目前用的模塊版本是多少

**Comment by SaLTNEko** [comment]
检测器已更新 magisk-riru-lsposed-HMA全部是最新版本 配置仅隐藏HMA黑名单适用软件买单吧app 配置存储后选择终止系统服务-重启 LSP开启对应模块-再次重启-使用新版检测器检测 依旧检测到了 日志请稍等
![1](https://user-images.githubusercontent.com/30261880/141333825-15d63dcd-4df6-486c-a1fb-71c9d8fe3125.jpg)
![2](https://user-images.githubusercontent.com/30261880/141333844-5223f3cb-eed4-42cc-8de6-743d72894a94.jpg)
![3](https://user-images.githubusercontent.com/30261880/141333879-53844b91-8029-4e9b-8a3f-51194c2c42c3.jpg)
![4](https://user-images.githubusercontent.com/30261880/141333889-d3f4c735-fb89-43be-a739-52f795eca7c6.jpg)

**Comment by gtgnb** [comment]
或许你应该把检测器也加入生效应用列表

**Comment by SaLTNEko** [comment]
已看到类似相关APP的问题 magisk检测与是否检测HMA无关 我的问题已经结束了 感谢您的回复
以及刚刚又尝试了一下仅HMA黑名单 对检测器生效的情况 且保存后停止了系统服务重启 但是依旧被检测到了

**Comment by cracky5322** [comment]
@gtgnb 他有加入，你往上拉可以看到，不過不知道為什麼沒有生效

**Comment by cracky5322** [comment]
@SaLTNEko 儲存後強制停止目標應用即可
你順便附上檢測器的設定

**Comment by SaLTNEko** [comment]
我刚刚理解错您的意思了 我以为是在设置服务里面去终止本身的系统服务 停止目标应用后再次检测已经没有爆红了 感谢您的答复
