### ISSUE TITLE
考虑做zygisk吗

### ISSUE THREAD

**Issue by Gong-Mi** [Dr-TSNG/Hide-My-Applist#111]
考虑做zy版本模块吗

**Comment by cracky5322** [comment]
@Gong-Mi 你有在官方頻道內嗎？

**Comment by Gong-Mi** [comment]
> @Gong-Mi 你有在官方頻道內嗎？
> 
> https://t.me/HideMyApplist

我不加电报群 所以问问

**Comment by cracky5322** [comment]
@Gong-Mi 所有答案都在裡面，這裡不額外進行回覆
