### ISSUE TITLE
无法完美隐藏edxposed包

### ISSUE THREAD

**Issue by huozijie1990** [Dr-TSNG/Hide-My-Applist#116]
使用edxposed框架的话，还是无法完美隐藏org.meowcat.edxposed.mananger包。（黑名单模式和白名单模式都试过了，过滤规则也添加了）。LSP框架没有这样的问题。

**Comment by cracky5322** [comment]
> 使用edxposed框架的話，還是無法完美隱藏org.meowcat.edxposed.mananger包。（黑名單模式和白名單模式都試過了，過濾規則也添加了）。LSP框架沒有這樣的問題。

不要问怎么隐藏 syscall，因为目前没做出来相关拦截
DO NOT report syscalls cannot be intercepted. We have NOT developed this yet

激活模块并重启后还是系统服务未运行的发 LSP 日志。（e什么d不提供技术支持，自求多福）
If after activating the module and restarting, still showing system service is not running, send the LSP log. (No technical support for edxp)
