### ISSUE TITLE
How to use in 'Multiple Users' setup

### ISSUE THREAD

**Issue by BurhanDanger** [Dr-TSNG/Hide-My-Applist#118]
I have 4 different users setup on my device. When trying to use this in another user I'm getting "Do not dual the module app, cause it will lead to config override." . How to make this app work in multiple users setup ?

**Comment by cracky5322** [comment]
> I have 4 different users setup on my device. When trying to use this in another user I'm getting "Do not dual the module app, cause it will lead to config override." . How to make this app work in multiple users setup ?

不要双开 HMA，因为这会导致配置被覆盖
DO NOT dual HMA, because it overrides configs

**Comment by BurhanDanger** [comment]
Apps on other users don't show for HMA that is installed on user 0. 

User 10 for example has different apps that are not present on user 0. How would I apply hiding on those ?

**Comment by cracky5322** [comment]
> Apps on other users don't show for HMA that is installed on user 0.
> 
> User 10 for example has different apps that are not present on user 0. How would I apply hiding on those apps ?

Does not support multiple users
