### ISSUE TITLE
招商银行和掌上生活app在需要Magsik模块的file和maps下闪退

### ISSUE THREAD

**Issue by TigerBest** [Dr-TSNG/Hide-My-Applist#120]
小米11U
MIUI 12.5.12 官版
Magsik 1c8ebfac-alpha （未开启Zygisk，但开启MagiskHide）

MHA 主程序 v2.2.4
MHA Magsik模块 v0.7.1

招行app和掌上生活在HMA中启用防止file和maps检测后会闪退，其他银行app无此问题

**Comment by cracky5322** [comment]
@TigerBest 那就是提醒你不要全選，沒必要隱藏就不用隱藏，這根本就不是問題
