### ISSUE TITLE
有一个我估计很难修复的bug

### ISSUE THREAD

**Issue by Zaphkito** [Dr-TSNG/Hide-My-Applist#123]
在部分机型上容易触发变砖，手上有一台三星 note FE和三星 note 8，都有极高的概率变砖（仅开启Riru，hidemyapplist的情况下就会变砖，与xposed无关）
另外Windows11上的安卓子系统百分百变砖
![image](https://user-images.githubusercontent.com/64299266/146650644-2b0ca70d-579d-4d49-9840-edec573275c4.png)

**Comment by keta1** [comment]
@Zaphkito 给日志...

**Comment by Zaphkito** [comment]
> @Zaphkito 给日志...

变砖后我怎么提日志……我估计最多就能提供个视频

**Comment by cracky5322** [comment]
@Zaphkito 先抓開機日誌
https://t.me/c/1188689189/601001

**Comment by Zaphkito** [comment]
![image](https://user-images.githubusercontent.com/64299266/146651110-ce3368e7-5f65-4598-b327-009d98e7e9ab.png)
![image](https://user-images.githubusercontent.com/64299266/146651120-97a8c12d-88d6-427b-98aa-8480c9509034.png)
[wsa.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/7739697/wsa.zip)
安卓子系统的，估计没啥用，我去复现一下三星 note fe的

**Comment by Zaphkito** [comment]
[惺惺惜note fe.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/7739723/note.fe.zip)
似乎抓取的是救砖后的日志emm

**Comment by Zaphkito** [comment]
另外我还发现在手机上即使不会变砖，开着这个模块也会产生各种奇奇怪怪的系统bug，安卓子系统因为百分百变砖所以不好说

**Comment by duzhaokun123** [comment]
@Zaphkito 有没有一种可能 你系统有问题

**Comment by Zaphkito** [comment]
> @Zaphkito 有没有一种可能 你系统有问题

星星星的表现主要是开机时间长（卡在第二屏且实际可进入系统，易触发救砖模块），关机按钮按下后延迟一段时间，关闭hidemyapplist后得到解决

**Comment by keta1** [comment]
@Zaphkito 把你的救砖模块检测时间设置长一点

**Comment by canyie** [comment]
@Zaphkito WSA 日志把 magisk hide 关掉再抓

**Comment by canyie** [comment]
另外你的三星日志里只加载了救砖模块， hma 根本没被加载，打开 riru 和 hma 关掉其他模块再抓一遍

**Comment by Dr-TSNG** [comment]
@canyie 停一停，wsa 烂的是已知原因，sepolicy 根本没被加载，这个问题已经修了，只是没推送，sepolicy 烂掉的情况以后会直接停止加载模块

**Comment by Zaphkito** [comment]
> 另外你的三星日志里只加载了救砖模块， hma 根本没被加载，打开 riru 和 hma 关掉其他模块再抓一遍

三星在开启riru和hma后触发bug开机日志抓取不到，之后只会抓取到救砖模块日志（

**Comment by Zaphkito** [comment]
> @canyie 停一停，wsa 烂的是已知原因，sepolicy 根本没被加载，这个问题已经修了，只是没推送，sepolicy 烂掉的情况以后会直接停止加载模块

所以以后WSA用不了吗

**Comment by Dr-TSNG** [comment]
@Zaphkito 你去问magisk，别问我，sepolicy不加载又不是hma的问题

**Comment by Zaphkito** [comment]
![Screenshot_20211219-175649_Chrome](https://user-images.githubusercontent.com/64299266/146670870-ac28fb7d-7eb6-4df8-94c3-6e2ef87d68b7.jpg)
![Screenshot_20211219-175507_TeamViewer](https://user-images.githubusercontent.com/64299266/146670876-ad102b33-6de3-403d-bc89-60ed648d3758.jpg)
![Screenshot_20211219-175547_TeamViewer](https://user-images.githubusercontent.com/64299266/146670880-895e6c35-2ee0-43df-b44d-f9c69199a402.jpg)
刚刚去提了个issue，wsa那边已经解决
