### ISSUE TITLE
[BUG] 屏幕和字体缩放太高的时候Manage Templates显示不全

### ISSUE THREAD

**Issue by tzfljuv** [Dr-TSNG/Hide-My-Applist#124]
MIUI，安卓11。其它ROM应该也有一样的问题。

开发者选项，最小宽度改到320，显示设置字体缩放改大。

然后Manage Templates底下就显示不出来了，也没法滑动。

暂时的Workaround是每次改Templates的时候手动改小缩放。

![Screenshot_2021-12-19-12-05-26-358_com tsng hidemyapplist](https://user-images.githubusercontent.com/36599326/146663523-a6c2575f-cdf0-483c-b2de-a26a1bad9ae0.jpg)

**Comment by tzfljuv** [comment]
另外首页最底下的About也显示不出来

**Comment by Dr-TSNG** [comment]
@tzfljuv 停一停，wsa烂的是已知原因，sepolicy根本没被加载，这个问题已经修了，只是没推送，sepolicy烂掉的情况以后会直接停止加载模块

**Comment by tzfljuv** [comment]
> @tzfljuv 停一停，wsa烂的是已知原因，sepolicy根本没被加载，这个问题已经修了，只是没推送，sepolicy烂掉的情况以后会直接停止加载模块

？？？回复错了吧？
