### ISSUE TITLE
Xposed hooks

### ISSUE THREAD

**Issue by iauei** [Dr-TSNG/Hide-My-Applist#125]
Hi, I have a problem, I try hide my Xposed, root, magisk, modules etc.

I use HideMyApplist and I configured everything except Xposed hooks. 

if i turn on Android Module Android Faker or any other, I see Xposed hooks - Found 

How to hide Xposed Hooks?

**Comment by cracky5322** [comment]
@iauei Is there only option system framework in LSPosed?

**Comment by iauei** [comment]
> @iauei Is there only option system framework in LSPosed?

I do not quite understand what you are writing about.
I have LSPosed with 2 modules Hide My Applist and Android Faker

If turn on Android Faker, AppListDetecrot will show an error Xposed hooks found

I only have this error, everything else is green.

**Comment by cracky5322** [comment]
@iauei What HMA chooses in LSPosed Manager

**Comment by cracky5322** [comment]
@iauei Discuss only here

**Comment by iauei** [comment]
@cracky5322 
Only system framework. 
https://i.postimg.cc/Sx3dWKCR/04.png

**Comment by cracky5322** [comment]
@iauei Screenshot of Android Faker in LSPosed manager

**Comment by iauei** [comment]
@cracky5322 

I did it differently here, and selected everything, and only the system framework or only applist detector

https://i.postimg.cc/yY5cGbdr/05.png

**Comment by cracky5322** [comment]
@iauei Cancel Applist Detector and HMA in Android Faker

**Comment by iauei** [comment]
yes, then there will be no error, because android faker will not work

but if I turn off Applist Detector in Android Faker then Applist Detector will see my real data. 

I want to use Android Faker to hide my data.

**Comment by cracky5322** [comment]
@iauei If you insist on turning on Android Faker for Applist Detector, then HOOK will be detected. This is not an error or a problem, I will close it.

**Comment by iauei** [comment]
@cracky5322 can you tell me how to solve this?


Hide-My-Applist made for Applist Detector, but if a person uses any module, then it can be seen Xposed Hooks found

**Comment by cracky5322** [comment]
@iauei Applist Detector is made for HMA. Your understanding is quite wrong. Since you have chosen HOOK, then we can’t prevent it. Don’t ask such stupid questions.

**Comment by iauei** [comment]
@iauei okay, sorry, but you can explain me how is it possible to hide Xposed Hooks?
 I cannot find this information anywhere, so I wrote it here

**Comment by cracky5322** [comment]
@iauei The best way is not to HOOK, there is no way to prevent HOOK from being detected

**Comment by iauei** [comment]
@cracky5322 please last question 

Is it possible to use programs like android faker to change phone data without using a hook?
how is it even called, how can I look for it?

**Comment by cracky5322** [comment]
@iauei And I need to remind you again, our job is to prevent app list detection, not to avoid HOOK detection. All the content displayed on the abnormal environment is only to assist users in determining why the detection is caused. If it is detected, we will not Will carry out any prevention and repair, please don't make unreasonable trouble
