### ISSUE TITLE
syscall file detection

### ISSUE THREAD

**Issue by iauei** [Dr-TSNG/Hide-My-Applist#126]
I want use Edxposed or Tai Chi, not LSposed.

And I have syscall file detection: found 

syscall file detection - org.meowcat.edxposed.manager - found

https://i.ibb.co/CHd4CfD/987.jpg

is there a module to help me hide this?

**Comment by Dr-TSNG** [comment]
No way. DO NOT USE DEAD FRAMEWORK.

**Comment by iauei** [comment]
ok, but if I use LSposed and modules like android faker, Applist Detector finds Xposed Hooks.

How can I hide Xposed hooks? 

do I need to rebuild it myself with different signatures (change class names)?

https://i.ibb.co/FXd3qXh/9879.png

**Comment by cracky5322** [comment]
@iauei Please stop asking stupid questions, if you want to use Android Faker for Applist Detector, you will definitely be detected Xposed HOOK

**Comment by canyie** [comment]
@iauei do not apply any module to ApplistDetector

**Comment by iauei** [comment]
@cracky5322 Look, we get to have the xposed jar of the framework itself, it depends on the xposed bridge api, which is also used in the modules. All detectors usually try to find bridge apy classes, because you can rename something in a popular module and framework, but both sides rely on the fact that the class names in the bridge will be exactly what they are. If the detector does not find the standard bridge classes by name, then even if the hooks are enabled, it will not be able to understand this.

**Comment by cracky5322** [comment]
@iauei This has never been HMA's job, please don't send any more spam
