### ISSUE TITLE
浏览器访问网页会自动跳到软件商店无法被拦截

### ISSUE THREAD

**Issue by tenwx** [Dr-TSNG/Hide-My-Applist#127]
RT，感觉像是scheme跳转，例如网页版百度首页新闻里的“百度APP内阅读”按钮，不知道是否可以拦截？

**Comment by cracky5322** [comment]
@tenwx 你的配置是怎樣丟出來看看，什麼都沒有是要我們求神問卜？還是巫毒看水晶？

**Comment by cracky5322** [comment]
@tenwx 看就知道是 Webview 而不是 Chrome

**Comment by cracky5322** [comment]
@tenwx 剛剛經過討論這是由系統決定，確認不能由 HMA 處理。
可能可以嘗試 IFW，不過可能要自己編寫規則，這不在我們的服務範圍，請自行研究。
https://github.com/Kr328/Riru-IFWEnhance
