### ISSUE TITLE
被隐藏应用列表统计小Bug

### ISSUE THREAD

**Issue by StrollStars** [Dr-TSNG/Hide-My-Applist#128]
这是一个比较小的瑕疵，模板中的被隐藏应用数量，可能和编辑列表中勾选的应用数量不完全一致，应该是前者大于后者，猜测可能由被隐藏应用卸载所致。

**Comment by cracky5322** [comment]
@StrollStars 已知問題

**Comment by PrinceBhai1** [comment]
Unzip error 😭

**Comment by PrinceBhai1** [comment]
Plz help me 🥺

**Comment by Dr-TSNG** [comment]
Expected，也许会加个按钮要不要自动删除已卸载的app配置
