### ISSUE TITLE
V2.3.2版本对于微信8.0.18启用隐藏时会引起不定时开始闪退

### ISSUE THREAD

**Issue by rinscr3003** [Dr-TSNG/Hide-My-Applist#131]
若对微信启用隐藏，则一段时间后（几小时到一两天）微信会突然闪退，而日志中看不到任何错误。

**Comment by TheInterestingSoul** [comment]
不要全部隐藏，开白名单模式，让微信扫到一两个无关紧要的应用；好多应用对扫应用列表处理不好，空列表直接挂掉

另外，用 https://github.com/TacoTheDank/Scoop 可以捕获到日志

**Comment by cracky5322** [comment]
沒有收到有效資訊，故關閉
