### ISSUE TITLE
已设置但并未生效

### ISSUE THREAD

**Issue by jiahe224** [Dr-TSNG/Hide-My-Applist#132]
设置如图：
黑名单模板
![698b80c9624b10aee25b2a07f85c809](https://user-images.githubusercontent.com/35186992/151160732-83c5017e-f28a-47ef-90fc-a3462be207d5.jpg)
![3e7e4c6de44398c01ccb90f22137b0e](https://user-images.githubusercontent.com/35186992/151160755-47cf39bf-5b23-4108-8bad-dbacfe51fcc7.jpg)
依然可以检测到
![a659c685bf09c5ec440bc6802b7b2b8](https://user-images.githubusercontent.com/35186992/151160790-832d184f-acd2-40f9-99da-64fa8ff46b46.jpg)

顺便求求怎么才能搞定国家政务服务呢，刚装完magisk并隐藏自身，然后禁用国家政务的s服务可正常启动，装了几个模块后又不行了，快疯了

**Comment by cracky5322** [comment]
如果有問題請依據要求提供所需資訊，如提出疑問不提供必要資訊我們會無視你的問題。
手機型號：

Android 版本：
ROM：
Magisk 版本：
Magisk 模塊列表：
LSPosed 版本：
LSPosed 模塊列表：

某些情況下，我們可能需要日誌，請附上 Magisk 日誌與 LSPosed 日誌
如果你的設備無法正常啟動，請附上開機日誌
開機日誌取得方式：
使用电脑:
https://t.me/hzrtools/12
使用magisk20.4+:
https://t.me/hzrtools/10

**Comment by jiahe224** [comment]
暂时用不到了，用 MyAndroidTool 解决了
