### ISSUE TITLE
Is there any way to hide a folder from an app using this module?

### ISSUE THREAD

**Issue by amitcoolcampus** [Dr-TSNG/Hide-My-Applist#136]
Is there any way to hide a folder from an app using this module?
I can see there are some options for additional maps and additional param rules. But not sure if they can do the needful. If yes then how to use them.
Some Banking apps have started detecting Twrp folder and they work when we rename twrp folder. So it would be great if we can mask twrp folder from banking apps.

**Comment by cracky5322** [comment]
@amitcoolcampus This is a hidden app, not a hidden folder, stop making unreasonable demands

**Comment by anshulm352** [comment]
> Is there any way to hide a folder from an app using this module? I can see there are some options for additional maps and additional param rules. But not sure if they can do the needful. If yes then how to use them. Some Banking apps have started detecting Twrp folder and they work when we rename twrp folder. So it would be great if we can mask twrp folder from banking apps.

Try XPL and XPL Pro
