### ISSUE TITLE
pubg new state discover installation package 

### ISSUE THREAD

**Issue by mahmoud32xn** [Dr-TSNG/Hide-My-Applist#138]
There is a problem PUBG New State detects the application package Please make the application with a different package name or make it random when installing

**Comment by Aritro37** [comment]
@mahmoud32xn This is not a problem with the application list and is contrary to the original design of the module

**Comment by mahmoud32xn** [comment]
> @ mahmoud32xn هذه ليست مشكلة في قائمة التطبيقات ومخالفة للتصميم الأصلي للوحدة

يتم تعطيل اللعبه عندما يتم تثبيت التطبيق وعند تثبيته تغلق يجب تغير حزمه التطبيق الخاص بالاخفاء حتى لا يكتشف أنه مثبت

**Comment by keta1** [comment]
Why not use HMA to hide yourself?
The random package name function will not be introduced!
I suggest you modify the package name and compile it yourself.
Next version, PUBG WILL UNSUPPORTED DUE TO MANY SPAM ABOUT IT
I recommend you UNINSTALL HMA

**Comment by mahmoud32xn** [comment]
> Why not use HMA to hide itself? The random package name function will not be introduced! I suggest you modify the package name and compile it yourself. Next version, PUBG WILL UNSUPPORTED DUE TO MANY SPAM ABOUT IT I recommend you UNINSTALL HMA

I want to change this com.tsng.hidemyapplist

**Comment by mahmoud32xn** [comment]
> > Why not use HMA to hide itself? The random package name function will not be introduced! I suggest you modify the package name and compile it yourself. Next version, PUBG WILL UNSUPPORTED DUE TO MANY SPAM ABOUT IT I recommend you UNINSTALL HMA
> 
> I want to change this com.tsng.hidemyapplist

When I install hidemyapplist The game PUBG New State does not work when I removed it hidemyapplist The game works, the game detects the name of a package com.tsng.hidemyapplist
