### ISSUE TITLE
Snapchat Crashes on Ads

### ISSUE THREAD

**Issue by DavidBerdik** [Dr-TSNG/Hide-My-Applist#139]
It seems that a recent update to Snapchat is causing crashes when ads load. The app freezes and crashes. This is what I see in the logs whenever this happens.

```
2022-02-15 00:14:01 [HMA Xposed] [INFO] @Hide PMS caller: com.snapchat.android method: getPackageInfo param: projekt.substratum
2022-02-15 00:14:02 [HMA Xposed] [INFO] @Hide PMS caller: com.snapchat.android method: getPackageInfo param: com.bitstrips.imoji
```

**Comment by cracky5322** [comment]
> It seems that a recent update to Snapchat is causing crashes when ads load. The app freezes and crashes. This is what I see in the logs whenever this happens.
> 
> ```
> 2022-02-15 00:14:01 [HMA Xposed] [INFO] @Hide PMS caller: com.snapchat.android method: getPackageInfo param: projekt.substratum
> 2022-02-15 00:14:02 [HMA Xposed] [INFO] @Hide PMS caller: com.snapchat.android method: getPackageInfo param: com.bitstrips.imoji
> ```

If you have any questions, please provide the required information. If you do not provide necessary information, we will ignore and delete your question.

Phone model:
Android version:
ROM:
Magisk version:
List of Magisk modules:
LSPosed version:
List of LSPosed modules:

In some cases, we may need the log, please attach Magisk log and LSPosed log
If your device cannot boot normally, please attach the boot log
How to get the boot log: 
with PC: 
https://t.me/hzrtools/12
with magisk20.4+ to catch log:
https://t.me/hzrtools/10

**Comment by DavidBerdik** [comment]
Phone model: Pixel 3 XL

Android version: 12

ROM: PixelExperience

Magisk version: 24.1

List of Magisk modules:

- App Systemizer (Terminal Emulator) v17.3.1
- Blobmoji Emoji 14, release 2
- Busybox for Android NDK 1.34.1
- Enhanced mode for HideMyApplist v1.0
- Universal SafetyNet Fix v2.2.1
- Enhanced mode for Storage Isolation (Zygisk) v26.0.1
- LSPosed (Zygisk) v1.7.2

LSPosed version: v1.7.2 (6379) - Zygisk

List of LSPosed modules:

- Disable-FLAG_SECURE v2.0.0
- Hide My Applist v2.3.2
- Pixel Mods v1.2.2

Magisk log: [magisk_log_2022-02-15T16_05_37.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/8074770/magisk_log_2022-02-15T16_05_37.log)

LSPosed log: [LSPosed_2022-02-15T16_06_02.061.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/8074775/LSPosed_2022-02-15T16_06_02.061.zip)

Here is a video demonstrating the crash. Notice how when the ad starts, the countdown to skip the advertisement is frozen at "Continue in 6...". You obviously cannot see this in the video, but when I try to skip the ad or press the back button, nothing happens, and the "not responding" dialog pops up. Please ignore the stupidity of the content I used for creating the demo. I just chose something random for it.

https://user-images.githubusercontent.com/7663225/154149699-68f060a4-0dea-4f48-bb75-b0746930037c.mp4

**Comment by cracky5322** [comment]
> Phone model: Pixel 3 XL
> 
> Android version: 12
> 
> ROM: PixelExperience
> 
> Magisk version: 24.1
> 
> List of Magisk modules:
> 
> * App Systemizer (Terminal Emulator) v17.3.1
> * Blobmoji Emoji 14, release 2
> * Busybox for Android NDK 1.34.1
> * Enhanced mode for HideMyApplist v1.0
> * Universal SafetyNet Fix v2.2.1
> * Enhanced mode for Storage Isolation (Zygisk) v26.0.1
> * LSPosed (Zygisk) v1.7.2
> 
> LSPosed version: v1.7.2 (6379) - Zygisk
> 
> List of LSPosed modules:
> 
> * Disable-FLAG_SECURE v2.0.0
> * Hide My Applist v2.3.2
> * Pixel Mods v1.2.2
> 
> Magisk log: [magisk_log_2022-02-15T16_05_37.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/8074770/magisk_log_2022-02-15T16_05_37.log)
> 
> LSPosed log: [LSPosed_2022-02-15T16_06_02.061.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/8074775/LSPosed_2022-02-15T16_06_02.061.zip)
> 
> Here is a video demonstrating the crash. Notice how when the ad starts, the countdown to skip the advertisement is frozen at "Continue in 6...". You obviously cannot see this in the video, but when I try to skip the ad or press the back button, nothing happens, and the "not responding" dialog pops up. Please ignore the stupidity of the content I used for creating the demo. I just chose something random for it.
> 
>  Snapchat.Crash.Demo.mp4

Why do you need to enable HMA for Snapchat?

It works fine without HMA

**Comment by Dr-TSNG** [comment]
@cracky5322 Open hma app, enable detail log, clear logs, open Snapchat, trigger bug, send the hma log

**Comment by Dr-TSNG** [comment]
> Phone model: Pixel 3 XL
> 
> Android version: 12
> 
> ROM: PixelExperience
> 
> Magisk version: 24.1
> 
> List of Magisk modules:
> 
> * App Systemizer (Terminal Emulator) v17.3.1
> * Blobmoji Emoji 14, release 2
> * Busybox for Android NDK 1.34.1
> * Enhanced mode for HideMyApplist v1.0
> * Universal SafetyNet Fix v2.2.1
> * Enhanced mode for Storage Isolation (Zygisk) v26.0.1
> * LSPosed (Zygisk) v1.7.2
> 
> LSPosed version: v1.7.2 (6379) - Zygisk
> 
> List of LSPosed modules:
> 
> * Disable-FLAG_SECURE v2.0.0
> * Hide My Applist v2.3.2
> * Pixel Mods v1.2.2
> 
> Magisk log: [magisk_log_2022-02-15T16_05_37.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/8074770/magisk_log_2022-02-15T16_05_37.log)
> 
> LSPosed log: [LSPosed_2022-02-15T16_06_02.061.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/8074775/LSPosed_2022-02-15T16_06_02.061.zip)
> 
> Here is a video demonstrating the crash. Notice how when the ad starts, the countdown to skip the advertisement is frozen at "Continue in 6...". You obviously cannot see this in the video, but when I try to skip the ad or press the back button, nothing happens, and the "not responding" dialog pops up. Please ignore the stupidity of the content I used for creating the demo. I just chose something random for it.
> 
>  Snapchat.Crash.Demo.mp4

Open hma app, enable detail log, clear logs, open Snapchat, trigger bug, send the hma log

**Comment by DavidBerdik** [comment]
> Why do you need to enable HMA for Snapchat?
> 
> It works fine without HMA

Enabling it for Snapchat is not strictly necessary for the app to work, but I would still like to use it because:

>- Device Information. We collect information from and about the devices you use. For example, we collect:
>
>    -   information about your hardware and software, such as the hardware model, operating system version, device memory, advertising identifiers, unique application identifiers, apps installed, unique device identifiers, browser type, keyboards installed, language, battery level, and time zone;

Source: https://snap.com/en-US/privacy/privacy-policy



> Open hma app, enable detail log, clear logs, open Snapchat, trigger bug, send the hma log

Here is the requested log: [hma_logs_02-16_14-30-36.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/8082938/hma_logs_02-16_14-30-36.log)

The app that it appears to be looking for in this case is [Bitmoji](https://play.google.com/store/apps/details?id=com.bitstrips.imoji) which I do not have installed on my phone.

**Comment by keta1** [comment]
> > Why do you need to enable HMA for Snapchat?
> > It works fine without HMA
> 
> Enabling it for Snapchat is not strictly necessary for the app to work, but I would still like to use it because:
> 
> > * Device Information. We collect information from and about the devices you use. For example, we collect:
> >   
> >   * information about your hardware and software, such as the hardware model, operating system version, device memory, advertising identifiers, unique application identifiers, apps installed, unique device identifiers, browser type, keyboards installed, language, battery level, and time zone;
> 
> Source: https://snap.com/en-US/privacy/privacy-policy
> 
> > Open hma app, enable detail log, clear logs, open Snapchat, trigger bug, send the hma log
> 
> Here is the requested log: [hma_logs_02-16_14-30-36.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/8082938/hma_logs_02-16_14-30-36.log)
> 
> The app that it appears to be looking for in this case is [Bitmoji](https://play.google.com/store/apps/details?id=com.bitstrips.imoji) which I do not have installed on my phone.
Can you provide a log of when Snapchat crash?
Use adb logcat to capture

**Comment by DavidBerdik** [comment]
> Can you provide a log of when Snapchat crash?
> Use adb logcat to capture

So, to work around the Snapchat issue, I disabled app list hiding so it would be usable. To capture the log that you requested, I obviously need to enable it again, however, I am unable to do so because for whatever reason, Snapchat does not show up in my list of installed apps whenever I try to use the Hide My Applist app.

**Comment by keta1** [comment]
> > Can you provide a log of when Snapchat crash?
> > Use adb logcat to capture
> 
> So, to work around the Snapchat issue, I disabled app list hiding so it would be usable. To capture the log that you requested, I obviously need to enable it again, however, I am unable to do so because for whatever reason, Snapchat does not show up in my list of installed apps whenever I try to use the Hide My Applist app.

Not long ago we found a bug
Do you have whitelist mode and Intent queries enabled?
Try turning off Intent queries
This issue will be fixed in the next release

**Comment by DavidBerdik** [comment]
> Not long ago we found a bug
> Do you have whitelist mode and Intent queries enabled?
> Try turning off Intent queries
> This issue will be fixed in the next release

Yes! I've been using Snapchat with whitelist mode and all hiding methods enabled.

It took several tries of reloading the Hide My Applist app before Snapchat would even show in the list of installed applications, but once it did, I made the changes to enable whitelist mode as well as all hiding methods except for Intent queries, and that seems to have worked. Snapchat is not crashing when ads load.

I am looking forward to the next release!

**Comment by cracky5322** [comment]
> > Not long ago we found a bug
> > Do you have whitelist mode and Intent queries enabled?
> > Try turning off Intent queries
> > This issue will be fixed in the next release
> 
> Yes! I've been using Snapchat with whitelist mode and all hiding methods enabled.
> 
> It took several tries of reloading the Hide My Applist app before Snapchat would even show in the list of installed applications, but once it did, I made the changes to enable whitelist mode as well as all hiding methods except for Intent queries, and that seems to have worked. Snapchat is not crashing when ads load.
> 
> I am looking forward to the next release!

Try this test version
[V2.3.3.r290.b4ee063-release](https://github.com/Dr-TSNG/Hide-My-Applist/suites/5390456273/artifacts/169703820)

**Comment by DavidBerdik** [comment]
> Try this test version
> [V2.3.3.r290.b4ee063-release](https://github.com/Dr-TSNG/Hide-My-Applist/suites/5390456273/artifacts/169703820)

Unfortunately, I may have spoke too soon. Even though Snapchat did not freeze during my initial testing after reenabling all hide methods except for Intent queries, it did freeze in a future attempt, and even after updating to this test version, it it still happening.

I do not understand what is going on with Snapchat not always showing up in the Hide My Applist app. I kind of wonder if perhaps Snapchat is actively trying to prevent Hide My Applist from functioning properly.

**Comment by Ipr6666** [comment]
تيتونيوثي

**Comment by DavidBerdik** [comment]
Are there any updates on this ticket?

**Comment by cracky5322** [comment]
@DavidBerdik Try the latest Ci version [V2.3.3.r296.9cab90a-release](https://github.com/Dr-TSNG/Hide-My-Applist/suites/5431757531/artifacts/172126775)

There may be a slight change, the developers are currently focusing on other projects
There is no guarantee that there will be future updates

**Comment by DavidBerdik** [comment]
@cracky5322 I certainly will once I get an opportunity to. I did notice that this project seems to have quieted down quite a bit recently. Very unfortunate, to be honest. This project is extremely useful and I would hate to see it die.

**Comment by DavidBerdik** [comment]
I suppose I should have updated this ticket to report that I don't see this issue with the latest CI/CD build. 😁

**Comment by DavidBerdik** [comment]
@cracky5322 You're welcome! 😊
