### ISSUE TITLE
[bug]不能抢在其他应用开机启动之前生效

### ISSUE THREAD

**Issue by brijagstu7** [Dr-TSNG/Hide-My-Applist#14]
开发者你好，我怀疑目前的版本不能抢在其他应用开机启动之前生效。因为我试了一下开机的时候打开微信可以看得到微x模块（这个App理应被隐藏的），而在强制结束微信然后再打开就看不到微x模块了。

**Comment by Dr-TSNG** [comment]
新版本已解决（更新后第一次重启还是需要手动打开app一次，之后就不需要了）
