### ISSUE TITLE
أكتشاف بعض التطبيقات من تثبيت الحزمه com.tsng.hidemyapplist

### ISSUE THREAD

**Issue by mahmoud32xn** [Dr-TSNG/Hide-My-Applist#140]
There are some applications that will not run during the installation of Hide My App. Is it possible to change this package? com.tsng.hidemyapplist To be under a different name so that the applications are not recognized and discovered

**Comment by cracky5322** [comment]
> There are some applications that will not run during the installation of Hide My App. Is it possible to change this package? com.tsng.hidemyapplist To be under a different name so that the applications are not recognized and discovered

Please do not send spam messages, this is the last warning
