### ISSUE TITLE
I have a problem, why has it not been answered? 

### ISSUE THREAD

**Issue by mahmoud32xn** [Dr-TSNG/Hide-My-Applist#141]
I have a problem and I want to solve it, I am a person who used the application and it is a very wonderful application, but I have a problem that I want to answer and I will not post again, I promise

**Comment by cracky5322** [comment]
> I have a problem and I want to solve it, I am a person who used the application and it is a very wonderful application, but I have a problem that I want to answer and I will not post again, I promise

Your problem can be handled by HMA without adding additional functions, so please don't keep sending spam messages.

**Comment by cracky5322** [comment]
@mahmoud32xn

**Comment by cracky5322** [comment]
> I have a problem and I want to solve it, I am a person who used the application and it is a very wonderful application, but I have a problem that I want to answer and I will not post again, I promise

We have tested it without any problems
https://imgur.com/a/cKYzDJW
