### ISSUE TITLE
Please listen to me to solve my problem 

### ISSUE THREAD

**Issue by mahmoud32xn** [Dr-TSNG/Hide-My-Applist#143]
I was using your application and it works perfectly and wonderfully, but when I scan the PUBG New State game through the Google Play store, I see that the new update for the game is discovering the application of Hide My App is not and the game refuses to open This happens to the latest version of the game from the Google Play Store, the old versions are working, but the latest version of the game does not open with your application

**Comment by mahmoud32xn** [comment]
This happens to the latest version of the game. You can try on the latest version of the game

**Comment by mahmoud32xn** [comment]
https://play.google.com/store/apps/details?id=com.pubg.newstate Try the latest version

**Comment by Dr-TSNG** [comment]
blocked spam

**Comment by cracky5322** [comment]
> https://play.google.com/store/apps/details?id=com.pubg.newstate Try the latest version

I used the brand new installation when you reported
https://imgur.com/a/ITzLEsu

It's always been your problem, not HMA's problem, please don't be unreasonable
