### ISSUE TITLE
Only a small confusion

### ISSUE THREAD

**Issue by Abdullah3119** [Dr-TSNG/Hide-My-Applist#147]
Is it important to select hidden apps (effective apps) in lsposed manager also. (I know u thinking, what dam 😓)
i mean here 

![20220228_023358](https://user-images.githubusercontent.com/76131717/155900831-25056cf4-bf46-44b1-a58e-ba2299fbbf83.jpg)

If you still not understand that what i want to ask (otherwise skip this paragraph) SUPPOSE i want to hide app A from app X with HMA. Do i need to select any of these app (app A and app X) in the given screenshot.

Sorry for my stupid question and my English.

**Comment by cracky5322** [comment]
invalid question
