### ISSUE TITLE
magisk模块似乎与Android 13不兼容

### ISSUE THREAD

**Issue by ender-zhao** [Dr-TSNG/Hide-My-Applist#150]
在目前最新的安卓版本中安装zygisk_magisk模块后会卡重启

设备：pixel 5
安卓版本：13
版本号：redfin-tpp1.220114.016

一并安装的其它模块：
Busybox for Android NDK
Move Certificates
Shamiko
Universal SafetyNet Fix
Zygisk - Enhanced mode for Storage Isolantion
Zygisk - LSPosed
Zygisk - Sui

**Comment by cracky5322** [comment]
@ender-zhao 請提供有效 log 一週內未提供會關閉此議題。

**Comment by cracky5322** [comment]
為提供有效資訊，故關閉
