### ISSUE TITLE
Why did this module update by itself? Malware?

### ISSUE THREAD

**Issue by vroad** [Dr-TSNG/Hide-My-Applist#156]
The module updated by itself today and I got a notification from LSposed about update. In my understanding Xposed modules won't update unless I manually update. Did my module installation contain malware or something? I re-installed v2.3.2 from GitHub just to be sure.

**Comment by Dr-TSNG** [comment]
1. All Xposed part of the module is fully open source.
2. Check your Google Play

**Comment by vroad** [comment]
Sorry, as you said, the module is on Google  Play and it s auto update was turned on.
