### ISSUE TITLE
应用列表搜索不到momo检测器

### ISSUE THREAD

**Issue by httpsColon** [Dr-TSNG/Hide-My-Applist#157]
我安装了这个 ![image](https://user-images.githubusercontent.com/102579986/163453448-27b5e3f1-49ef-4663-bb16-2e10c3854c64.png)

在hide my applist 模板管理里的编辑列表却搜不到momo
![image](https://user-images.githubusercontent.com/102579986/163454000-0a2c876f-7fc1-464f-be30-fd208089a585.png)
，然而系统应用管理和magisk排除列表里搜得到momo
![image](https://user-images.githubusercontent.com/102579986/163453856-51970225-700f-4404-b47a-4908f3124e68.png)
![image](https://user-images.githubusercontent.com/102579986/163453884-9f81ccce-e067-45d7-a5a3-5f6e57a2638c.png)

**Comment by cracky5322** [comment]
@httpsColon MOMO 並不檢測包名稱，你對他啟用也沒有效果，且對 MOMO hook 後會使 MOMO 無效。

如果設備使用上沒有任何問題請無視 MOMO
