### ISSUE TITLE
[Bug] I can't hide a module

### ISSUE THREAD

**Issue by Maikol2502** [Dr-TSNG/Hide-My-Applist#159]
### Steps to reproduce/复现步骤

![Screenshot_20220423-174250553](https://user-images.githubusercontent.com/104281333/164948508-4c3d6aae-2f00-47a3-b34a-2e0c45181cee.jpg)

### Expected behaviour/预期行为

I should mark everyone on hooks, but it won't let me

### Actual behaviour/实际行为

It does not want to hide the module and I have already configured it a thousand times

### Xposed Module List/Xposed 模块列表

```Shell
Hide my app list
```

### Magisk Module List/Magisk 模块列表

```Shell
Hide my app list
Safety fix
Shamiko
Lsposed zygisk
```

### Hide-My-Applist version/Hide-My-Applist 版本

2.3.2

### Android version/Android 版本

11

### Magisk version/Magisk 版本

24.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of Hide-My-Applist and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

![Screenshot_20220423-174250553](https://user-images.githubusercontent.com/104281333/164948549-ed017c16-98c1-461e-9b29-37e07b30e807.jpg)

**Comment by cracky5322** [comment]
@Maikol2502 This is not a bug, XPrivacyLua must be removed manually after removing the folder /data/system/xlua

**Comment by Maikol2502** [comment]
Thanks You're the best
![Screenshot_20220423-175722099](https://user-images.githubusercontent.com/104281333/164948777-7a12a8cf-9cd3-4634-bd75-eb1b40be5b78.jpg)
