### ISSUE TITLE
How to use Map and Param rules in HMA.

### ISSUE THREAD

**Issue by anshulm352** [Dr-TSNG/Hide-My-Applist#160]
Hello team, There are two options in Template Maps Rules and Query Param Rules which say " Add Custom interception Rules "...
What are these features ??? Do we need to add the Process ID of the apps which we want to hide ??? I tried but found nothing interesting about these two options like what are they, for what they are used and how to use em ?? Please assist me. Thanks

**Comment by cracky5322** [comment]
@anshulm352 If you are willing to read in detail you will find the answer https://GitHub.com/Dr-tsng/hide-my-app list#document

**Comment by anshulm352** [comment]
> @anshulm352 If you are willing to read in detail you will find the answer https://GitHub.com/Dr-tsng/hide-my-applist#document

Sir, I have read the document as per your referral twice... What is confusing me is what to put i.e Process ID of the app which is detecting or package name of the same app...

Please I know it's cumbersome to explain something to someone newbie... Just give me an abstract view so I can surf more about it. Thanks.. A quick response will be appreciable...

**Comment by cracky5322** [comment]
@anshulm352 If you are a novice, then you do not need to use this function

**Comment by anshulm352** [comment]
pl

> @anshulm352 If you are a novice, then you do not need to use this function

Please sir, I want to know how and what is this option... An app called Applist detector by DrTSNG always detects some apps i.e XPrivacy Lua and it also detects Xposed hooks as well. I am trying to hide such intrusions..

**Comment by cracky5322** [comment]
@anshulm352 Why don't you try to search Issues for answers? I'll lock this pointless discussion.
