### ISSUE TITLE
Failed to install Magisk module

### ISSUE THREAD

**Issue by CharlotteFallices** [Dr-TSNG/Hide-My-Applist#161]
![Screenshot_20220505-122842.png](https://user-images.githubusercontent.com/47619464/166863930-03f627f9-0fc2-4fc9-9664-1b4f9a8df1a5.png)
The zip archieve has already renamed as it required

**Comment by cracky5322** [comment]
@CharlotteFallices 你的 zip 哪裡下載的

**Comment by cracky5322** [comment]
@CharlotteFallices 無法獲得有效資訊。
