### ISSUE TITLE
System framework not allowing system app to function

### ISSUE THREAD

**Issue by idanny76** [Dr-TSNG/Hide-My-Applist#164]
I have LSPosed with Hide my applist and it has a check mark on System Framework. Is there a way around that, because if I remove the check mark it goes into boot loop. If I leave the check mark the app doesn't work. If I disable the HMA, then it works. The magisk module I am trying to use is BCR Basic Call Recorder https://github.com/chenxiaolong/BCR
![Screenshot_2022-05-23-21-58-39-49_084ab3bc34f7aa7ccff83653f52abafc](https://user-images.githubusercontent.com/85074566/169933200-7a968c12-8f54-4f0f-b4bb-3fe6ec8a7df8.jpg)

**Comment by DuscaeJG** [comment]
Hello! Found this while searching on google because I have kinda the same issue. I accidentally removed the checkmark and then updated and now I'm stuck in a bootloop. Would you know how to get out of the bootloop?

**Comment by cracky5322** [comment]
@DuscaeJG I don't know how to start safe mode on your phone, maybe you can refer to [Disabling/uninstalling modules manually](https://www.didgeridoohan.com/magisk/MagiskModuleIssues#)

**Comment by idanny76** [comment]
> Hello! Found this while searching on google because I have kinda the same issue. I accidentally removed the checkmark and then updated and now I'm stuck in a bootloop. Would you know how to get out of the bootloop?

What I had to do was find the full firmware for my device of the version I was using when it happened. Then I did dirty update and It did not delete my data partition. Since I did not have TWRP, I did the update through fastboot adb commands. You can also use "adb sideload ota.zip" command. There is an ADB command to remove all the magisk modules....  https://didgeridoohan.com/magisk/Magisk#hn_Module_causing_issues_Magisk_functionality_bootloop_loss_of_root_etc

**Comment by idanny76** [comment]
> Hello! Found this while searching on google because I have kinda the same issue. I accidentally removed the checkmark and then updated and now I'm stuck in a bootloop. Would you know how to get out of the bootloop?

[Remove all modules](https://didgeridoohan.com/magisk/Magisk#)
Since Magisk v19.4, there's an adb command that can be used to uninstall all modules on your device. If the device is bootlooping or simply hanging on the boot animation you have a good chance that you can use this command to get up and running again.

Hook your device up to a computer (or other device you can run adb from) and execute the following command:

adb wait-for-device shell magisk --remove-modules


After that you can start your device and as soon as adb is available the command will activate, the modules will be removed and the device will reboot. Hopefully to a working system, sans modules. There's of course a chance that the troublesome module has done something that the command can't remove...

If you do not have USB Debugging enabled adb won't work and you'll need to use Safe Mode instead (see below).

**Comment by DuscaeJG** [comment]
@cracky5322 @idanny76 Many thanks to you both! My phone is now working I used one of the solutions in that page!
