### ISSUE TITLE
[Bug] Mi 12 Pro，安卓13（Mi12Pro-20220810-V13.1.22.8.3.DEV-13-zeus-ef25c769-2in1-Simplicity）不可用

### ISSUE THREAD

**Issue by Zerek-Cheng** [Dr-TSNG/Hide-My-Applist#165]
### Steps to reproduce/复现步骤

安装apk文件，激活lsposed内模块，授权magisk
安装magisk模块并启用后重启

### Expected behaviour/预期行为

正常服务

### Actual behaviour/实际行为

一旦启用magisk模块就卡米，无法生效

### Xposed Module List/Xposed 模块列表

```Shell
HideMyApplist
```

### Magisk Module List/Magisk 模块列表

```Shell
HideMyApplist
Shamiko
Universal SafetyNet Fix
Xiaomi CTS Pass
Zygisk-LSPosed
```

### Hide-My-Applist version/Hide-My-Applist 版本

2.3.2/2.3.3修改版均不行

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [x] I am using latest debug CI version of Hide-My-Applist and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

...

**Comment by cracky5322** [comment]
@Zerek-Cheng 移除 HideMyApplist Magisk 模塊就能正常開機了，無法開機的狀態移除方法請參閱 Magisk 官方教學

**Comment by ianchb** [comment]
@Zerek-Cheng 移除Magisk模块

**Comment by Zerek-Cheng** [comment]
> @Zerek-Cheng 移除 HideMyApplist Magisk 模塊就能正常開機了，無法開機的狀態移除方法請參閱 Magisk 官方教學

您好，移除后显示app内服务无法启动

**Comment by ianchb** [comment]
@Zerek-Cheng 你这反馈里2.3.2/2.3.3也不是最新的ci……

**Comment by cracky5322** [comment]
Continue to extend the question, so close the discussion
