### ISSUE TITLE
[Bug] Android 13 , system service not running.

### ISSUE THREAD

**Issue by xfangbao** [Dr-TSNG/Hide-My-Applist#167]
### Steps to reproduce/复现步骤

lsposed 1.8.3 6552
Magisk 25200 Zygisk模式

### Expected behaviour/预期行为

-

### Actual behaviour/实际行为

-

### Xposed Module List/Xposed 模块列表

```Shell
-
```

### Magisk Module List/Magisk 模块列表

```Shell
-
```

### Hide-My-Applist version/Hide-My-Applist 版本

-

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25200

### Riru version/Riru 版本

-

### Version requirement/版本要求

- [X] I am using latest debug CI version of Hide-My-Applist and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

-

**Comment by copystring** [comment]
Hello @Dr-TSNG,
I've updated to Android 13 the other day. When enabling the Magisk Module the phone get's stuck while booting. In Fact it seems it almost fully boots but does not switch to the Google logo to actual android.
At that point adb shell works. Also su works in adb shell.
Disabling the Magisk modules makes the phone work fine again.
You marked this as spam. Does that mean you'll not make the magisk module support Android 13?

Kind regards

Felix

**Comment by DavidBerdik** [comment]
I assume that @Dr-TSNG closed this as spam because the bug report is missing a load of important information. I have opened a proper bug report on the issue.

https://github.com/Dr-TSNG/Hide-My-Applist/issues/168
