### ISSUE TITLE
[Bug] Issue with Multiple profile environment (i.e. Island setup) on Android 12.1

### ISSUE THREAD

**Issue by cooldroid** [Dr-TSNG/Hide-My-Applist#172]
### Steps to reproduce/复现步骤

Install the Hide-My-Applist module on Lsposed (zygisk)

### Expected behaviour/预期行为

The module should work just fine :)

### Actual behaviour/实际行为

It just goes into the loop of injecting the hook and leads to soft reboot.

### Xposed Module List/Xposed 模块列表

```Shell
Hide-My-Applist
```

### Magisk Module List/Magisk 模块列表

```Shell
LSposed (zygisk)
```

### Hide-My-Applist version/Hide-My-Applist 版本

3.0.0

### Android version/Android 版本

12.1

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of Hide-My-Applist and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-08-24T12_00_54.996.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/9413525/LSPosed_2022-08-24T12_00_54.996.zip)

**Comment by Dr-TSNG** [comment]
Try this

[app-debug.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/9413885/app-debug.zip)

**Comment by cooldroid** [comment]
> Try this
> 
> [app-debug.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/9413885/app-debug.zip)

Yes! This one seems to be working fine :)
