### ISSUE TITLE
App crash after Beta Update 3.0.0

### ISSUE THREAD

**Issue by slimshouki** [Dr-TSNG/Hide-My-Applist#182]
App crashes whenever module is hooked and strangely it crashes other apps like truecaller and wa tweaker. I cant open the app to send you the logs when the module is hooked. However, I can open it only if the module is unhooked in lsposed.
![Screenshot_20220825-100310_Shell](https://user-images.githubusercontent.com/74891073/186610171-667fe4b1-9917-4e11-ac91-d5e5651a12ac.png)
![Screenshot_20220825-100252_Shell](https://user-images.githubusercontent.com/74891073/186610183-9e66a886-85aa-4269-af1c-f3f3971c0231.png)

**Comment by slimshouki** [comment]
Same crash on Beta 3.0.2

**Comment by ianchb** [comment]
@slimshouki seems the same question for me many versions ago, but it works fine now on my device now. Can you give logs for further information?

**Comment by Dr-TSNG** [comment]
Use AppErrorsTracking to get bug report
https://github.com/KitsunePie/AppErrorsTracking/releases
Remember to install DEBUG version instead of release version in
https://github.com/Dr-TSNG/Hide-My-Applist/actions

**Comment by slimshouki** [comment]
> Use AppErrorsTracking to get bug report https://github.com/KitsunePie/AppErrorsTracking/releases Remember to install DEBUG version instead of release version in https://github.com/Dr-TSNG/Hide-My-Applist/actions

Here you go
[com.tsng.hidemyapplist_1661421622008.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/9423664/com.tsng.hidemyapplist_1661421622008.log)

**Comment by Dr-TSNG** [comment]
Fixed at 611e27148ec73e2a23765e4684371eda20989d52

**Comment by PeterNjeim** [comment]
I have the same issue as well, patiently await your next official release (hopefully very soon as this issue is urgent for me (currently just disabled HMA as a workaround)). Don't feel like building it myself currently. Thanks again.

**Comment by ianchb** [comment]
@PeterNjeim Check in Actions: Fix crash when hide hma for gms

**Comment by slimshouki** [comment]
Appreciate your hard work. If its possible, can u share test apk after commit change to check issue is fixed or nt.

**Comment by slimshouki** [comment]
> @PeterNjeim Check in Actions: Fix crash when hide hma for gms

We r waiting for a test version

**Comment by PeterNjeim** [comment]
> We r waiting for a test version

What do you mean? There's debug and release, no such thing as "test"

**Comment by PeterNjeim** [comment]
I tested it, it works! Thanks for the quick fix

**Comment by PeterNjeim** [comment]
I stand corrected, still broken for me lol. I opened the app too early then

**Comment by PeterNjeim** [comment]
I mean, it does fix the HMA crash issue, but other apps still crash too

**Comment by PeterNjeim** [comment]
[logcat_08-25-2022_22-24-55.txt](https://github.com/Dr-TSNG/Hide-My-Applist/files/9429107/logcat_08-25-2022_22-24-55.txt)

**Comment by ianchb** [comment]
@slimshouki CI builds are in Github Actions.

**Comment by Dr-TSNG** [comment]
@PeterNjeim You should ether not hide apps for gms or hide gms for the apps at the same time

**Comment by PeterNjeim** [comment]
I'm a little confused. I have my template with many apps invisible, and I have applied the template to many others apps (which includes GMS). I don't use GMS in both the invisible and applied categories, so I'm not sure what I'm supposed to do here

**Comment by PeterNjeim** [comment]
I removed GMS from the applied category, this works, however I'm not sure why I didn't need to do this on Android 12, maybe this is an Android 13 issue?

**Comment by Dr-TSNG** [comment]
@PeterNjeim I think the problem may be, the app found gms, and try to communicate with it, but gms cannot find the app (or vise versa), this caused the crash. If it is this reason, nothing can I do to fix because it's "intended behavior". So there are two solutions: don't hide gms for apps and don't hide apps for gms; hide gms for apps and hide apps for gms at the same time.

**Comment by PeterNjeim** [comment]
I tried enabling GMS in both the invisible and applied categories, but unfortunately I'm getting the same logcat errors. So I will have to disable GMS from both categories instead to allow the apps to work. I'm not sure why it worked in Android 12 though. I will instead make a new template dedicated for apps that don't use GMS, and hide GMS from those apps. Thanks for the help

**Comment by slimshouki** [comment]
All working perfectly after gms crash.

**Comment by NFG-Hooks** [comment]
3.0.3-Beta crashes too after updating from 3.0.2

**Comment by cracky5322** [comment]
@NFG-Hooks If you have any new questions please open a new issues

**Comment by Dr-TSNG** [comment]
> 3.0.3-Beta crashes too after updating from 3.0.2

Reboot

**Comment by NFG-Hooks** [comment]
> > 3.0.3-Beta crashes too after updating from 3.0.2
> 
> Reboot

reply here or do i need to open a new issue ?
anyway i already rebooted my device and the it's the same ...can i provide you any thing to help fixing it ?

**Comment by Dr-TSNG** [comment]
> > > 3.0.3-Beta crashes too after updating from 3.0.2
> > 
> > 
> > Reboot
> 
> reply here or do i need to open a new issue ? anyway i already rebooted my device and the it's the same ...can i provide you any thing to help fixing it ?

Create a new issue, and provide info as the instruction
