### ISSUE TITLE
[Bug] Applist Detector检测出Xposed hooks

### ISSUE THREAD

**Issue by Mahmood002** [Dr-TSNG/Hide-My-Applist#184]
### Steps to reproduce/复现步骤

1.安装Hide My Applist并于LSPosed启用
2.安装Applist Detector
3.设置Applist Detector为白名单模式

### Expected behaviour/预期行为

Applist Detector无法检测出异常

### Actual behaviour/实际行为

Applist Detector检测出了Xposed hooks并且PM Intent Queries栏提示可疑。

### Xposed Module List/Xposed 模块列表

```Shell
Hide My Applist
```

### Magisk Module List/Magisk 模块列表

```Shell
Shamiko
Zygisk - LSPosed
```

### Hide-My-Applist version/Hide-My-Applist 版本

3.0.2-Beta-352

### Android version/Android 版本

11

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of Hide-My-Applist and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[日志文件（包含Magisk，LSPosed，HMA）](https://www.swisstransfer.com/d/8a8ad063-956a-4957-886d-0ee398f2b3de)

**Comment by Dr-TSNG** [comment]
但凡看过帮助页都知道作用域只勾系统框架
