### ISSUE TITLE
[Question] HMA cant hide itself

### ISSUE THREAD

**Issue by xAffan** [Dr-TSNG/Hide-My-Applist#188]
I'm using ruru applist detector which has enhanced detection for sys/libc I'm guessing.

With bind mount option off
![Screenshot_2022-08-26-15-13-33-247_com byxiaorun detector](https://user-images.githubusercontent.com/59138135/186886346-7fa257e2-ad87-412b-b748-681934a3241b.jpg)

With bind mount option on
![Screenshot_2022-08-26-15-13-18-818_com byxiaorun detector](https://user-images.githubusercontent.com/59138135/186886386-d6551ff8-34f5-4a8a-98a4-eb97109b291a.jpg)

My xposed module list
![Screenshot_2022-08-26-15-21-44-131_com android shell](https://user-images.githubusercontent.com/59138135/186886457-f949e13e-3be8-4ab1-a795-1f2116bd541e.jpg)

I have no idea how to download debug version.

**Comment by cracky5322** [comment]
Please use "Bug report" to report, and fill in the information in detail
