### ISSUE TITLE
[Bug] 双卡手机只能检测到一个SIM卡

### ISSUE THREAD

**Issue by games579** [Dr-TSNG/Hide-My-Applist#189]
### Steps to reproduce/复现步骤

安装“隐藏应用列表”后，重启后只能检测到一张SIM卡
卸载“隐藏应用列表”后，重启恢复了正常

### Expected behaviour/预期行为

安装并重启，手机能正常检测到手机的两张SIM卡，并且能使用

### Actual behaviour/实际行为

安装并重启后，手机只能检测到一张SIM卡，并且也只能使用一张sim卡

### Xposed Module List/Xposed 模块列表

```Shell
安装器接管
miui高级设置
哔哩漫游
核心破解
墨•息 
墨•状态栏歌词
微x模块
隐藏应用列表
运动修改器
godvip
idm辅助追踪
JustTrustMe
miui主题破解
miui遮罩进化
miuihome
NoANR
QNotified
Telegram内容限制解除
WooBoxForMIUI
XAutoDaily
scene5
```

### Magisk Module List/Magisk 模块列表

```Shell
H-无障碍服务守护[ASGuard]
shamiko
LSPosed
小黄鸟系统证书
新内核墓碑 [Google Freezer]
神仙自助就砖
防miui检测更新
```

### Hide-My-Applist version/Hide-My-Applist 版本

HMA-V3.0.0-Beta_352

### Android version/Android 版本

Android 12

### Magisk version/Magisk 版本

magisk 25.2(25200)

### Version requirement/版本要求

- [X] I am using the latest [CI debug build](https://github.com/Dr-TSNG/Hide-My-Applist/actions) of Hide-My-Applist with detail log for debugging enabled/我正在使用最新 [CI 调试版本](https://github.com/Dr-TSNG/Hide-My-Applist/actions) 且启用详细日志

### Logs/日志

[Uploading magisk_log_2022-08-27T09.11.22.log…]()

**Comment by keta1** [comment]
请等日志上传完毕再发布

现在需要你重新发一次日志

**Comment by cracky5322** [comment]
超過 24 小時沒有收到任何有效資訊，故關閉此問題
