### ISSUE TITLE
3.0.2beta不生效

### ISSUE THREAD

**Issue by huoyan1231** [Dr-TSNG/Hide-My-Applist#190]
### Steps to reproduce/复现步骤

对应用使用隐藏
打开应用

### Expected behaviour/预期行为

被应用隐藏的应用无法检测到隐藏的应用

### Actual behaviour/实际行为

隐藏无效果

### Xposed Module List/Xposed 模块列表

```Shell
哔哩漫游
非残！
核心破解
剪贴板过滤器
贴吧TS
微X模块
隐藏应用列表
知了
chimi
custommiuizer13
deepsleep
fuckmimarket
lucky patcher
mipush enhance
miui原生通知图标
MIUI麻醉师
miui遮罩进化
qauxiliary
qq瘦身
qx模块
r安装组件扩展
scene4
thanox
tsbattery
woobox for miui
xposed edge pro
xprivacy lua
```

### Magisk Module List/Magisk 模块列表

```Shell
a1内存管理
h无障碍守护
huotouch
quickswitch
scene附加模块
shamiko
universe gms doze
universe safetynet fix
uperfv3+sa
lsposed
sui
新内核墓碑
淦MIUI温控
深度doze
爱玩机工具箱拓展
救砖模块
```

### Hide-My-Applist version/Hide-My-Applist 版本

3.0.2beta

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.2（25200）

### Version requirement/版本要求

- [X] I am using the latest [CI debug build](https://github.com/Dr-TSNG/Hide-My-Applist/actions) of Hide-My-Applist with detail log for debugging enabled/我正在使用最新 [CI 调试版本](https://github.com/Dr-TSNG/Hide-My-Applist/actions) 且启用详细日志

### Logs/日志

[hma_logs_2022-08-27_10.10.34.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/9437139/hma_logs_2022-08-27_10.10.34.log)

**Comment by cracky5322** [comment]
@huoyan1231 使用 [ApplistDetector](https://github.com/Dr-TSNG/ApplistDetector) 並且截圖，同時提供提示檢的應用

**Comment by cracky5322** [comment]
@huoyan1231 超過 24 小時為提供有效資訊

**Comment by huoyan1231** [comment]
> @huoyan1231 使用 [ApplistDetector](https://github.com/Dr-TSNG/ApplistDetector) 並且截圖，同時提供提示檢的應用

![Screenshot_2022-08-31-01-52-53-278_icu.nullptr.applistdetector.jpg](https://user-images.githubusercontent.com/53113734/187508613-91b917ee-1a92-4116-999f-e8b15a004dbe.jpg)![Screenshot_2022-08-31-01-53-12-042_com.tsng.hidemyapplist.jpg](https://user-images.githubusercontent.com/53113734/187508636-3d262151-9895-405f-9836-c019c5f05ec9.jpg)
检的应用指什么？

**Comment by cracky5322** [comment]
@huoyan1231 將設定備份後上傳上來

**Comment by huoyan1231** [comment]
[HMA_Config.json.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/9458730/HMA_Config.json.log)
麻烦手动删除.log
升级到3.0.4Beta仍不可用

**Comment by Dr-TSNG** [comment]
更新后是否重启并打开过一次app再进行测试

**Comment by huoyan1231** [comment]
> 

有的 
不起作用

**Comment by Dr-TSNG** [comment]
发送一下 /system/framework/framework.jar

**Comment by huoyan1231** [comment]
> 发送一下 /system/framework/framework.jar，顺便告知下手机品牌

红米K40G（M2012K10C）
https://www.mediafire.com/file/52rbnp17pa9bfzg/framework.jar/file

**Comment by huoyan1231** [comment]
更新至[V3.0.4-Beta.r362.d22ac92-release](https://github.com/Dr-TSNG/Hide-My-Applist/suites/8118111730/artifacts/351280097)后恢复正常
