### ISSUE TITLE
App Crashes after upgrading to 3.0.3-Beta

### ISSUE THREAD

**Issue by NFG-Hooks** [Dr-TSNG/Hide-My-Applist#192]
Hmmm
well, the app was working fine, but after updating and rebooting the device the app started to crashe i hooked the app and thought it was the problem ..unhooked it and still the same 

LSposed 1.8.3-(6552) Riru release 
Android version => 11
Magisk Alpha latest version (25202)
What else can i provide you ?

**Comment by cracky5322** [comment]
@NFG-Hooks Please use "Bug report" to fill in the necessary information to report the problem
