### ISSUE TITLE
[Bug] App crash

### ISSUE THREAD

**Issue by NFG-Hooks** [Dr-TSNG/Hide-My-Applist#193]
### Steps to reproduce/复现步骤

1.Upgrade the app to 3.0.3 Beta
2.Rebooting the device 
3.Opening the app

### Expected behaviour/预期行为

the app should work normally but it didn't

### Actual behaviour/实际行为

Crashed every time i tried to open it

### Xposed Module List/Xposed 模块列表

```Shell
Hide My Applist and
1.Android Faker
2.Core patch
3.Device ID Masker lite
4.Devoptshide
5.Disable flage secure
6.firefds-kit(R)
7.Force Dark
8.Lucky Patcher
9.NFG Multi Crack
10.No Storage Restrict
11.Pixelify GPhotos
12.Prvacy Space
13.Revenue Cat
14.Simple hook
15.源计划
16.SSLunpinning
17.Thanox
18.Weiju
19.XprivacyLua
```

### Magisk Module List/Magisk 模块列表

```Shell
1.Block Ads
2.BusyBox For AndroidNDK
3.Dex2oat Optimizer
4.ExSDcard Access enabler
5.input Power control
6.Liboemcrypto disabler
7.Magisk Drm disabler
8.Move Certificates
9.No Storage Restricte
10.Overlay Fs
11.Riru
12.Lsposed
13.Riru momo hider
14.Riru Play integrity fix
```

### Hide-My-Applist version/Hide-My-Applist 版本

V3.0.3-Beta

### Android version/Android 版本

11

### Magisk version/Magisk 版本

Magisk Alpha  c5c608f0-alpha(25202)

### Version requirement/版本要求

- [x] I am using the latest [CI debug build](https://github.com/Dr-TSNG/Hide-My-Applist/actions) of Hide-My-Applist with detail log for debugging enabled/我正在使用最新 [CI 调试版本](https://github.com/Dr-TSNG/Hide-My-Applist/actions) 且启用详细日志

### Logs/日志

[logcat_08-30-2022_10-14-05.txt](https://github.com/Dr-TSNG/Hide-My-Applist/files/9451063/logcat_08-30-2022_10-14-05.txt)
i got this log using logreader app !!
after rebooting and trying to open the app it crashes tried to install 3.0.2 beta version to see the logs but it's empty ...knowing that i have enabled detail log for debugging

**Comment by NFG-Hooks** [comment]
i installed this version 3.0.3-Beta.r359.36dab92
and installed app errors tracking i got this 
[com.tsng.hidemyapplist_1661848505349.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/9451298/com.tsng.hidemyapplist_1661848505349.log)

**Comment by Dr-TSNG** [comment]
Someone submitted wrong translation which breaks string format. What's your language?

**Comment by NFG-Hooks** [comment]
> Someone submitted wrong translation which breaks string format. What's your language?

Arabic !!

**Comment by Dr-TSNG** [comment]
https://github.com/Dr-TSNG/Hide-My-Applist/runs/8088730402

**Comment by NFG-Hooks** [comment]
> https://github.com/Dr-TSNG/Hide-My-Applist/actions/runs/2955071185

👍 it's working now
