### ISSUE TITLE
[Bug] Can't boot when using v3.0.0+

### ISSUE THREAD

**Issue by KiGamji** [Dr-TSNG/Hide-My-Applist#195]
### Steps to reproduce/复现步骤

Install and enable in LSPosed Hide My Applist version 3.0.0+.

### Expected behaviour/预期行为

Should boot normally

### Actual behaviour/实际行为

Hangs at the final stage of the boot animation, doesn't rebooting.

### Xposed Module List/Xposed 模块列表

```Shell
CustoMIUIzer, Lucky Patcher, Hide My Applist, XPrivacyLua (disabled).
```

### Magisk Module List/Magisk 模块列表

```Shell
Busybox for Android NDK, Shamiko, Zygisk - LSPosed, Universal SafetyNet Fix, MagiskHide Props Config.
```

### Hide-My-Applist version/Hide-My-Applist 版本

HMA-V3.0.3-Beta.r361.5b47e5c-release

### Android version/Android 版本

10

### Magisk version/Magisk 版本

25.2

### Version requirement/版本要求

- [x] I am using the latest [CI debug build](https://github.com/Dr-TSNG/Hide-My-Applist/actions) of Hide-My-Applist with detail log for debugging enabled/我正在使用最新 [CI 调试版本](https://github.com/Dr-TSNG/Hide-My-Applist/actions) 且启用详细日志

### Logs/日志

[logcat.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/9455679/logcat.zip)

**Comment by ianchb** [comment]
@KiGamji I checked your log, you are using Arabic right?

**Comment by ianchb** [comment]
@KiGamji If so, use this CI build: https://github.com/Dr-TSNG/Hide-My-Applist/actions/runs/2955071185

**Comment by ianchb** [comment]
@KiGamji Please uninstall the Magisk module of HMA. it's not needed when using 3.0.0+.

**Comment by KiGamji** [comment]
> Please uninstall the Magisk module of HMA.

Thank you so much, everything is working now!

**Comment by ajmz** [comment]
> @KiGamji 
> Please uninstall the Magisk module of HMA. it's not needed when using 3.0.0+.
> 
> 08-30 23:35:31.513  1346  1346 I [HMA Native]: Magisk extension start. Version 1.0 (35)

请问是在magisk里面添加到“配置排除列表”吗？
而且我也手动删除了/data/system/hide_my_applist_* ，但重启都无法进入系统。
HMA 3.0.5版本。

![Screenshot_20221026004708.png](https://user-images.githubusercontent.com/30185045/197849728-ef9ec5c7-56ca-420c-bc92-cdb061105fd4.png)
