### ISSUE TITLE
Hide not available

### ISSUE THREAD

**Issue by DrSaad77** [Dr-TSNG/Hide-My-Applist#196]
### Steps to reproduce/复现步骤

Hello, hide is not available.
When I install apk version of 1.6.1 everything is working fine. Unfortunately when I update the app HMA through PlayStore, I am not more able to select the model created to Hide selected apps from PlayStore.
When I choose the Google Playstore and try to select created model, it is not available in the list.
![Screenshot_20220902_120456](https://user-images.githubusercontent.com/36936960/188105056-90b4f885-1854-406d-8c3c-02e3adf47a82.jpg)

### Expected behaviour/预期行为

Hide model not available 

### Actual behaviour/实际行为

Hide model not available 

### Xposed Module List/Xposed 模块列表

```Shell
Hide My app app/module, used with LSPosed
```

### Magisk Module List/Magisk 模块列表

```Shell
- Magisk BootLoop Protector
- Universal SafetyNet fix
- Youtube Revanced
- Zygisk LSPosed
```

### Hide-My-Applist version/Hide-My-Applist 版本

2.3.2

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.2

### Version requirement/版本要求

- [X] I am using the latest [CI debug build](https://github.com/Dr-TSNG/Hide-My-Applist/actions) of Hide-My-Applist with detail log for debugging enabled/我正在使用最新 [CI 调试版本](https://github.com/Dr-TSNG/Hide-My-Applist/actions) 且启用详细日志

### Logs/日志

None

**Comment by cracky5322** [comment]
@DrSaad77 When posting issues, please use [CI](https://github.com/Dr-TSNG/Hide-My-Applist/actions/runs/2955071185) to confirm if there is a problem first

**Comment by Dr-TSNG** [comment]
3.0.4 is released but you are still using 2.3.2, and you don't even look at the version requirement table

**Comment by DrSaad77** [comment]
Sorry It got update alone from playstore, that is why I am on that 2.3.2 version.
Anyway I installed latest beta 3.0.4, and still same. Hide not available 
![Uploading Screenshot_20220902_160442.jpg…]()

**Comment by cracky5322** [comment]
@DrSaad77 Screenshots are uploaded correctly, please re-upload and provide HMA_Config through the backup function.

**Comment by NFG-Hooks** [comment]
Hello, I have no issues. but is the search icon will exist at the stable build? It's helpful and Speeds up the process of finding applications

**Comment by DrSaad77** [comment]
> @DrSaad77 Screenshots are uploaded correctly, please re-upload and provide HMA_Config through the backup function.

Here is the Screenshot, and backup config as requested

**Comment by DrSaad77** [comment]
Here is the Screenshot, and backup config as requested
![Screenshot_20220902_160442](https://user-images.githubusercontent.com/36936960/188179471-8ae506c0-a7ec-4816-a849-eae28e09841d.jpg)
How to upload a file please??
Here is what is present in the backup file

{"configVersion":85,"detailLog":false,"maxLogSize":512,"forceMountData":true,"templates":{"PlayStore":{"isWhitelist":false,"appList":["com.google.android.apps.youtube.music","com.google.android.youtube"]}},"scope":{"com.android.vending":{"useWhitelist":true,"excludeSystemApps":false,"applyTemplates":[],"extraAppList":[]}}}

**Comment by DrSaad77** [comment]
Here how the app looks like if it may help
![Screenshot_20220902_181405](https://user-images.githubusercontent.com/36936960/188180922-380cd45c-55e3-47a0-814c-fd1b25933a84.jpg)
![Screenshot_20220902_181414](https://user-images.githubusercontent.com/36936960/188180937-996a7ca1-9d0f-4cfb-9d14-ae74030940a9.jpg)
![Screenshot_20220902_181434](https://user-images.githubusercontent.com/36936960/188180953-130bc9cb-d746-463e-a20a-ad8af5b6aa04.jpg)
![Screenshot_20220902_181517](https://user-images.githubusercontent.com/36936960/188180959-c7202957-ade8-4440-b068-2646440fc329.jpg)

**Comment by cracky5322** [comment]
@DrSaad77 Try this
[HMA_Config test.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/9479217/HMA_Config.test.zip)

**Comment by Dr-TSNG** [comment]
You created a blacklist template, why on earth do you think you can find it on a whitelisted app.

**Comment by DrSaad77** [comment]
> You created a blacklist template, why on earth do you think you can find it on a whitelisted app.

because I installed this module long ago when settings where a bit different.
I used this tuto
![Vanced Hide Magisk 24+ (2)](https://user-images.githubusercontent.com/36936960/188193571-ab81f9a2-f2cf-48a6-9763-fae436c4fcba.jpg)
And I never created any white list, only Blaklist.
In second step, it says create Blacklist templete, and that is what I did long ago, and was working fine.
Until recent version.

![Vanced Hide Magisk 24+ (4)](https://user-images.githubusercontent.com/36936960/188193826-f474525f-8a85-4612-8ed0-9162857fbdb8.jpg)

**Comment by DrSaad77** [comment]
I tried the config Test and now hide templete is available
![Screenshot_20220902_190456](https://user-images.githubusercontent.com/36936960/188194493-e468f759-8198-4c68-a433-8e6659b4639c.jpg)

**Comment by cracky5322** [comment]
@DrSaad77 That's because you created a black list template and then you selected a white list in PLAY, so you can't see the black list template you created and all the errors are of your own making

**Comment by DrSaad77** [comment]
You were right, and I am sorry. guess we did not understand each other. You were talking about this toggle. My back I did not have to enable it. Indeed when it is enable, no model is available.
![Screenshot_20220902_191148](https://user-images.githubusercontent.com/36936960/188195521-fe8985a6-7022-4f03-8bb7-c5e83b11ed82.jpg)

**Comment by DrSaad77** [comment]
Google app still available through Google PlayStore for update even after PlayStore data and Cache deleted and followed with a restart. And for Service Google Playstore also.
![Screenshot_20220902_192836](https://user-images.githubusercontent.com/36936960/188198221-f1999288-122d-4ba0-b367-be7146224586.jpg)

**Comment by ianchb** [comment]
@DrSaad77 Seams it's off topic, you may open a new issue if you have other problems.
