### ISSUE TITLE
閃退[Bug] 

### ISSUE THREAD

**Issue by GMXWHU** [Dr-TSNG/Hide-My-Applist#197]
### Steps to reproduce/复现步骤

進入app直接閃退

### Expected behaviour/预期行为

正常進入頁面

### Actual behaviour/实际行为

閃退

### Xposed Module List/Xposed 模块列表

```Shell
.
```

### Magisk Module List/Magisk 模块列表

```Shell
.
```

### Hide-My-Applist version/Hide-My-Applist 版本

3.0.4beta

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25.2

### Version requirement/版本要求

- [X] I am using the latest [CI debug build](https://github.com/Dr-TSNG/Hide-My-Applist/actions) of Hide-My-Applist with detail log for debugging enabled/我正在使用最新 [CI 调试版本](https://github.com/Dr-TSNG/Hide-My-Applist/actions) 且启用详细日志

### Logs/日志

[LSPosed_2022-09-02T21_32_53.227846.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/9478255/LSPosed_2022-09-02T21_32_53.227846.zip)

**Comment by Dr-TSNG** [comment]
App 崩溃请使用 [AppErrorsTracking](https://github.com/KitsunePie/AppErrorsTracking) 而不是 lsp 日志

**Comment by cracky5322** [comment]
數日未獲得更詳細的資訊，故關閉
