### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by shiluI** [Dr-TSNG/Hide-My-Applist#199]
### Steps to reproduce/复现步骤

之前用的很老的版本一直没问题，今天更新到3.0.4以后重启后系统桌面无响应。
经过排除确认为隐藏应用列表APP的问题。该问题可通过［强制清理运行环境］得到暂时性解决，到重新打开APP并再次重启手机手bug复现。

### Expected behaviour/预期行为

系统正常运行

### Actual behaviour/实际行为

系统桌面无响应

### Xposed Module List/Xposed 模块列表

```Shell
储存重定向
不要多管闲事
对话框取消
核心破解
thanox
```

### Magisk Module List/Magisk 模块列表

```Shell
busybox
MIUI补全优化
shamiko
zygisk-LSPosed
爱玩机工具箱
自动神仙救砖-防冻版
```

### Hide-My-Applist version/Hide-My-Applist 版本

V3.0.4

### Android version/Android 版本

安卓11

### Magisk version/Magisk 版本

25.2

### Version requirement/版本要求

- [X] I am using the latest [CI debug build](https://github.com/Dr-TSNG/Hide-My-Applist/actions) of Hide-My-Applist with detail log for debugging enabled/我正在使用最新 [CI 调试版本](https://github.com/Dr-TSNG/Hide-My-Applist/actions) 且启用详细日志

### Logs/日志

[ INFO] 09-03 13:14:47 (HMA-Service) Config file not found
[ INFO] 09-03 13:14:47 (PmsHookTarget30) Load hook
[ INFO] 09-03 13:14:47 (ZygoteArgsHook) Load hook
[ INFO] 09-03 13:14:47 (HMA-Service) Hooks installed
[ INFO] 09-03 13:14:47 (HMA-Service) HMA service initialized
[ INFO] 09-03 13:14:47 (HMA-Bridge) Bridge service initialized
[ INFO] 09-03 13:31:15 (ZygoteArgsHook) @startViaZygote force mount data: 1000 com.miui.cleanmaster
[ INFO] 09-03 13:41:12 (ZygoteArgsHook) @startViaZygote force mount data: 1000 com.miui.cleanmaster

**Comment by Dr-TSNG** [comment]
https://github.com/Dr-TSNG/Hide-My-Applist/actions/runs/2983385641

**Comment by cracky5322** [comment]
數日未獲得更詳細的資訊
