### ISSUE TITLE
need video tutorial

### ISSUE THREAD

**Issue by mortaza01** [Dr-TSNG/Hide-My-Applist#2]
please upload a video tutorial in youtube plz 
🙏

**Comment by Dr-TSNG** [comment]
Not considered recently since there is going to be some big updates in next versions(current version is not consummate), including better usage instructions and a lot of UI changes. I'll make it easier to figure out how to use.

**Comment by wildanie** [comment]
when you release the stable version soon

**Comment by Dr-TSNG** [comment]
I think the help information in the current version is detailed enough. If you don't understand something, please join the telegram group.
