### ISSUE TITLE
模板名称无法改名

### ISSUE THREAD

**Issue by soulpursuit** [Dr-TSNG/Hide-My-Applist#20]
![Screenshot_2021-05-12-00-43-17-693_com tsng hidemyapplist](https://user-images.githubusercontent.com/48674277/117853970-97c79500-b2bb-11eb-805a-8e5be96d0000.jpg)
![Screenshot_2021-05-12-00-46-58-160_com tsng hidemyapplist](https://user-images.githubusercontent.com/48674277/117853980-9a29ef00-b2bb-11eb-8221-0e70b22e6e5f.jpg)

无法修改名称，长按只能删除

**Comment by Dr-TSNG** [comment]
2.0 已解决

**Comment by soulpursuit** [comment]
感谢！！！
意思今晚有望发布2.0？😍

**Comment by Dr-TSNG** [comment]
@soulpursuit CI 已发布，但是配置迁移没有写完，所以 stable 还早，可以下来尝鲜，但最好等稳定版

**Comment by Aritro37** [comment]
@soulpursuit 你要闲聊你就进群闲聊。。。在github闲聊算啥
