### ISSUE TITLE
[Bug] HMA doesn't work for Libc&Syscall File Detection

### ISSUE THREAD

**Issue by Young-Lord** [Dr-TSNG/Hide-My-Applist#214]
### Steps to reproduce/复现步骤

1. 禁用不相关的 Magisk 与 Xposed 模块
2. 安装 HMA 与 Applist Detector，作用域选择系统框架，创建白名单模板并为 Applist Detector应用，重启
3. 打开 Applist Detector，运行检测

（系统是 MIUI 12.5，Magisk Delta 25.2）

### Expected behaviour/预期行为

对“存储空间隔离”的检测全部为“Not Found”

### Actual behaviour/实际行为

![检测结果](https://user-images.githubusercontent.com/51789698/193434588-825ec927-670e-4f92-85d0-fda3b5b62661.jpg)

仅在`Libc File Detection`与`Syscall File Detection`检测出“存储空间隔离”

### Xposed Module List/Xposed 模块列表

```Shell
隐藏应用列表
```

### Magisk Module List/Magisk 模块列表

```Shell
Riru    v26.1.7.r530.ab3086ec9f（最新版）
Riru - Enhanced mode for Storage Isolation    v28.0.1
Riru - LSPosed    v1.8.4 (6609)
```

### Hide-My-Applist version/Hide-My-Applist 版本

V3.0.5-Beta.r373.b2bd9a4-debug

### Android version/Android 版本

11

### Magisk version/Magisk 版本

25.2

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

[logs.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/9691488/logs.zip)

**Comment by Dr-TSNG** [comment]
删除 Android/data 下相关目录

**Comment by Young-Lord** [comment]
好了，感谢（绝了）

**Comment by Stemp123** [comment]
Syscall and Libc is also detected for me on org.lsposed.manager

Everything else is undetected
