### ISSUE TITLE
Can't boot on 1.4 and later

### ISSUE THREAD

**Issue by dcoolArne** [Dr-TSNG/Hide-My-Applist#22]
The phone boots normaly, but touch is not working to insert sim pin and after a few sekonds the screen turns off and cannot be switched on again. When i just boot my device with the app installed but not activated in edxposed the phone also needs a lot longer to boot and after the first update from 1.3.3 multipel apps crash direktly after the installation. My phone is a S9, with android 10 and magisk 22.1, latest riru and latest edxposed. I tried to captcher a log with android Studio.
[phonelog.txt](https://github.com/Dr-TSNG/Hide-My-Applist/files/6468745/phonelog.txt) The log is with the latest Hide-My-Applist version on edxposed manager.

**Comment by Dr-TSNG** [comment]
Does the non-native version crashes too?

**Comment by dcoolArne** [comment]
The 1.5.4 non native version works for me. But is it expected that the other version completely crashes my phone even when the xposed part is not activated?
