### ISSUE TITLE
[Bug] bootloop with EdXposed

### ISSUE THREAD

**Issue by aaazv** [Dr-TSNG/Hide-My-Applist#220]
### Steps to reproduce/复现步骤

1. install the latest version of hma
2. Activate in edxposed
3. Restart

### Expected behaviour/预期行为

Boot normally

### Actual behaviour/实际行为

Bootloop

### Xposed Module List/Xposed 模块列表

```Shell
Xposed edge pro
XposedSmsCode
GravityBox [R]
Greenify
Lucку-Patcher
NekoSMS
DevOptsHide
Disable-FLAG_SECURE
Firefds Kit [R]
```

### Magisk Module List/Magisk 模块列表

```Shell
Riru
Busybox
Riru - edxposed
```

### Hide-My-Applist version/Hide-My-Applist 版本

V3.0.5-beta

### Android version/Android 版本

11

### Magisk version/Magisk 版本

23

### Version requirement/版本要求

Other/其他

### Logs/日志

Idk how to.

**Comment by Dr-TSNG** [comment]
**NEVER** support edxp
