### ISSUE TITLE
[Bug] Bootloop with EdXposed

### ISSUE THREAD

**Issue by aaazv** [Dr-TSNG/Hide-My-Applist#221]
### Steps to reproduce/复现步骤

1. installing module
2. Activate
3. Reboot

### Expected behaviour/预期行为

boot normally

### Actual behaviour/实际行为

bootloop

### Xposed Module List/Xposed 模块列表

```Shell
Xposed edge pro
XposedSmsCode
GravityBox [R]
Greenify
Lucку-Patcher
NekoSMS
DevOptsHide
Disable-FLAG_SECURE
Firefds Kit [R]
```

### Magisk Module List/Magisk 模块列表

```Shell
Riru
Busybox
Riru - edxposed
```

### Hide-My-Applist version/Hide-My-Applist 版本

V3.0.5-beta

### Android version/Android 版本

11

### Magisk version/Magisk 版本

23

### Version requirement/版本要求

Public release/beta version/公开发布/测试版

### Logs/日志

Having EdXposed 4.6.2 installed
With riru 25.4.4

**Comment by ianchb** [comment]
@aaazv Remove EdXposed, and stop sending invalid issues.
