### ISSUE TITLE
[Bug] System service not running 

### ISSUE THREAD

**Issue by kp-nikhil** [Dr-TSNG/Hide-My-Applist#228]
### Steps to reproduce/复现步骤

install apk
activate module in lsposed
reboot 

### Expected behaviour/预期行为

after installing and rebooting system service should start 

### Actual behaviour/实际行为

after reboot module is active but system service is not running even after clean run runtime environment

### Xposed Module List/Xposed 模块列表

```Shell
hide my app list
snapmod
telespeed
```

### Magisk Module List/Magisk 模块列表

```Shell
hide userdebug
lib storage companion for rooted samsung
riru
riru momo hider
riru youtube revanced
systemless hosts
universal safetynet fix
```

### Hide-My-Applist version/Hide-My-Applist 版本

v.r379.4b73057-debug

### Android version/Android 版本

13

### Magisk version/Magisk 版本

18aob94a-delta 

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

[Uploading LSPosed_2022-11-21T12_33_59.288013.zip…]()

**Comment by Dr-TSNG** [comment]
U can't even wait for the log to be uploaded completely, right?
