### ISSUE TITLE
[Bug] 太平保宝app设置隐藏无效，无法启动，闪退

### ISSUE THREAD

**Issue by cantonadong** [Dr-TSNG/Hide-My-Applist#231]
### Steps to reproduce/复现步骤

下载地址：https://img.life.cntaiping.com/tpbb/app/download/index.html
开启magisk和隐藏后，对这个app无效。强制闪退。

求帮忙解决。谢谢

### Expected behaviour/预期行为

正常启动运行

### Actual behaviour/实际行为

闪退

### Xposed Module List/Xposed 模块列表

```Shell
微x
```

### Magisk Module List/Magisk 模块列表

```Shell
lsposed
```

### Hide-My-Applist version/Hide-My-Applist 版本

3.0.5

### Android version/Android 版本

11

### Magisk version/Magisk 版本

25.2

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

[hma_logs_2022-11-28_21.13.25.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/10104003/hma_logs_2022-11-28_21.13.25.log)

**Comment by cracky5322** [comment]
@cantonadong 看到不知道該如何吐槽，有沒有一種可以能是檢測 root 而不是應用列表

**Comment by cantonadong** [comment]
我试过了，如果只开启root不启用 lsposed 是可以正常启动的。
