### ISSUE TITLE
[Bug] miui14(android13)刷后卡白米

### ISSUE THREAD

**Issue by AoEiuV020** [Dr-TSNG/Hide-My-Applist#235]
### Steps to reproduce/复现步骤

刚升的miui14, 双清了，
magisk zygisk 正常工作，
最新版Hide-My-Applist 2.3.2 应用内刷magisk模块，
重启手机，

### Expected behaviour/预期行为

正常使用，

### Actual behaviour/实际行为

卡白米，也就是开机动画页面，

### Xposed Module List/Xposed 模块列表

```Shell
WooBox For MIUI
贴吧TS
隐藏应用列表
```

### Magisk Module List/Magisk 模块列表

```Shell
zygisk-lsposed
shamiko
```

### Hide-My-Applist version/Hide-My-Applist 版本

23.2

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25.2

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

好像停更了？也懒得找日志了，随便记录一下吧，

**Comment by Dr-TSNG** [comment]
乐，自己用老版本不看更新提示怪模块

**Comment by QingHui653** [comment]
@Dr-TSNG 请问下 存储空间隔离怎么隐藏. 我已经在 hideMyAppList 中配置了 存储空间隔离.
但是使用 applist Detector  检测 还是 能检测出 moe.shizuku.redirectstorage 来.

现在就差这个无法隐藏了
