### ISSUE TITLE
[Bug] 'Apps Invisible' information is not properly refreshed...

### ISSUE THREAD

**Issue by pndwal** [Dr-TSNG/Hide-My-Applist#241]
### Steps to reproduce/复现步骤

1) Check only 1 app in Edit list of a template 
2) Close HMA
3) Uninstall app that was selected in template 
4) Open HMA, select same template in Template Manage...
5) Note Information is still "1 apps invisible"!...
6) Select Edit list... Note no (0) apps are checked/selected.

Nb. If multiple apps are selected, the information "x apps invisible" will no longer match number selected after any of these apps are uninstalled... Number selected with reduce but x won't (remains the same).

Nb. 2. The above anomaly also occurs w/ Apps Manage, "additional apps invisible"...

### Expected behaviour/预期行为

Number of Apps Invisible should match number checked in Edit list...

Number of Apps Invisible should reduce when apps in list are uninstalled rather than accumulate...

Refreshing lists should fix anomalies with "Apps Invisible" numbers given also...

### Actual behaviour/实际行为

HMA module seems to work fine! 🙂

However, after reinstalling Magisk hidden stub app multiple times (always with the same custom name) I must always add the hidden stub app in template again (as randomised package name changes?) which is expected behaviour, however Information now says "14 apps invisible" for my 'magisk' template while only 1 app is checked in Edit list, and there seems to be no way to correct the misinformation...

### Xposed Module List/Xposed 模块列表

```Shell
3.0.6-386
```

### Magisk Module List/Magisk 模块列表

```Shell
None
```

### Hide-My-Applist version/Hide-My-Applist 版本

HMA-V3.0.6.r392.227ba02-debug

### Android version/Android 版本

10 (MIUI 12.0.4)

### Magisk version/Magisk 版本

25205

### Version requirement/版本要求

Public release/beta version/公开发布/测试版

### Logs/日志

[hma_logs_2022-12-18_19.12.47.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/10253420/hma_logs_2022-12-18_19.12.47.zip)

**Comment by ianchb** [comment]
@pndwal Regarding your question, uninstalling the app after adding it to the template, the amount will not decrease - when you install the same app next time, it should appear in the template. In addition, the identification of the application here is based on the package name instead of the app name. When Magisk hides, it will randomly generate the package name, so it needs to be added again every time. *I noticed that you are already using the debug version of the CI build. When reporting a problem, please remember to select it, otherwise it will be closed by the robot.

**Comment by pndwal** [comment]
Thanks for responding ☺️

> @pndwal Regarding your question, uninstalling the app after adding it to the template, the amount will not decrease - when you install the same app next time, it should appear in the template.

Sure, I understand this... But this is still not expected behaviour at least for users since they will expect those 'x apps hidden' to exist in userspace...

The act of unchecking existing apps correctly reduces the 'apps invisible' number... Why shouldn't uninstalling (which also unchecks) do the same?... Especially since there's no way to correct 'apps invisible ' number once the app is gone... In the case of Magisk stub (which randomises package name) we can never get that package back, so HMA may say '150 apps hidden' even when only one app (Magisk obfuscated stub) was ever added to the template in question!...

There sould (at least) be a way to remove apps/package names that a user has uninstalled manually so this misinformation doesn't keep compounding...

> In addition, the identification of the application here is based on the package name instead of the app name. When Magisk hides, it will randomly generate the package name, so it needs to be added again every time.

Yes, understood this...

> *I noticed that you are already using the debug version of the CI build.

Actually I'm using the public release as indicated...

The bug report rules (at least in English) are confusing...

The template simply said to check and indicate debug build, not that it needs to be installed... I would have done this however if recently commits had indicated that this issue had been considered or addressed...

> When reporting a problem, please remember to select it, otherwise it will be closed by the robot.

But it's unclear what goes where!...

Eg, is 'Magisk Module List' for the older HMA Magisk (enhancement) module?... Maybe Magisk itself? Or LSPosed Magisk module?...

... Is 'Xposed Module List' the HMS Xposed module, or perhaps LSPosed itself?...

... What does 'Version requirement' mean since 4 options are given?... (is it really optional, or is it a trick with only one acceptable answer?)

Nothing is clear (in English), but I was going to have a crack at working all this out by trial and error (when I had time!)...

🙃 Kind regards, PW
