### ISSUE TITLE
Not hiding discord from playstore

### ISSUE THREAD

**Issue by pbanj** [Dr-TSNG/Hide-My-Applist#242]
I've been using hma for a long time, never had an issue. Was using the beta without issue. Today out of nowhere the playstore started seeing discord and updated it(I stay on an older version). I updated to the release of hma and it still finds it.

![log](https://media.discordapp.net/attachments/399670410565910529/1054852013986414592/Screenshot_20221220-145938_Hide_My_Applist.png)

Hmmm now it's blocking it again. I'll keep an eye on it and report back. Gonna close the issue for now.

**Comment by xerta555** [comment]
Hi
To hide app(s) from your PS app, i would recommend u to use another XPosed module(s) like SudoHide for exemple.
I use it for few apps on my side without any bugs.
