### ISSUE TITLE
[Bug] 在安卓 13 上无法选择应用或套用模板

### ISSUE THREAD

**Issue by fatinghenji** [Dr-TSNG/Hide-My-Applist#244]
### Steps to reproduce/复现步骤

1.安装 hide 
2.lsposed 中勾选
3.重启手机

### Expected behaviour/预期行为

1.成功创建隐藏列表
2.在`模版管理`中选择需要生效的应用
3.在`应用管理`选择需要应用的模板

### Actual behaviour/实际行为

1.在`模版管理`中的应用列表为空
![Screenshot_2022-12-29-10-30-19-89_6b8d254452bc4a3798e188525542e357](https://user-images.githubusercontent.com/37131177/209895487-53f2ded7-c4f7-443d-a6ba-ca1ed3dd639e.jpg)

![Screenshot_2022-12-29-10-27-29-00_6b8d254452bc4a3798e188525542e357](https://user-images.githubusercontent.com/37131177/209895364-9873e687-cd60-475d-a1fc-f482e5bd021e.jpg)

2.在`应用管理`模板列表为空
![Screenshot_2022-12-29-10-27-41-26_6b8d254452bc4a3798e188525542e357](https://user-images.githubusercontent.com/37131177/209895370-177c2979-0cdb-414a-95fe-0e282457ccc2.jpg)

### Xposed Module List/Xposed 模块列表

```Shell
Plusne
QAuxiliary
QQ 瘦身
Thanox Pro
X Privacy Lua
```

### Magisk Module List/Magisk 模块列表

```Shell
A-Soul Game Optimization 
Dfps
Scense 的附加模块
Shamiko
upfers
```

### Hide-My-Applist version/Hide-My-Applist 版本

V3.0.6

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25.2

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

[Uploading hma_logs_2022-12-29_10.37.43.log…]()

**Comment by fatinghenji** [comment]
[LSPosed_2022-12-29T10_46_22.173762.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/10317357/LSPosed_2022-12-29T10_46_22.173762.zip)
补充 lsposed 日志，似乎看到相关报错。

**Comment by Dr-TSNG** [comment]
expected，自行学习如何配置
