### ISSUE TITLE
[Bug] Issue With Play Store

### ISSUE THREAD

**Issue by NFG-Hooks** [Dr-TSNG/Hide-My-Applist#247]
### Steps to reproduce/复现步骤

1-Created a blacklist with Youtube & Plus Messenger.
2-Applied the Blacklist to Google play store

### Expected behaviour/预期行为

What is expected to happen that the store should work normally without any problems and i be able to install any app from the file manager 

### Actual behaviour/实际行为

1-Play store can't open ever and keep freezing on startup screen
2- Being unable to install any other app from the file manager

### Xposed Module List/Xposed 模块列表

```Shell
Hid My applist
Android faker
core patch
Dark tricks
firfds
Devopts hide
Darq
Disable flag secure
Gps Setter
HookVip
justtrust me
lucky patcher
killgram
Macsposed
NFG
NoVpnDetected
RVNcat hook
sslunpining
TeleSpeed 
Thanox
Secure plan
weiju
xposedsmscode
xprivacylua
Scene5 (disabled)
Pixel mods (disabled)
```

### Magisk Module List/Magisk 模块列表

```Shell
Busybox
Hex installer Module
input power control
Riru (disabled)
Riru isolated Magiskhide(disabled)
Riru lsposed (disable)
Scene5
USNF
Zygisk lsposed
```

### Hide-My-Applist version/Hide-My-Applist 版本

3.1.0-beta.r400.f09af4b Debug

### Android version/Android 版本

12

### Magisk version/Magisk 版本

Magisk Canary v831a398b (25206)

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

[hma_logs_2022-12-31_13.17.00.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/10327229/hma_logs_2022-12-31_13.17.00.log)

**Comment by NFG-Hooks** [comment]
any progress ?🤔

**Comment by NFG-Hooks** [comment]
@xerta555 
hmm 🤔, i do that because i don't want apps to being updated from play store like YouTube & Plus Messenger.
i don't do that because i want to hide a suspicious app.
As the Stable version (3.0.6) is working fine i didn't face this issue before.

**Comment by xerta555** [comment]
> hmm 🤔, i don't add it to the blacklist ..i apply a blacklist on it, so those apps can't be updated anymore.
> also it's not a known issue, since the Stable version 3.0.6 doesn't have it and every thing is working as i wanted.
> another thing this problem only happen when i enable vold app data option from the settings
> if i kept it off every thing going well the issue appears when enabling this option.

If you just want to prevent some of your applications from being automatically updated by the Play Store, then you don't need HMA for that.
Two Xposed modules exist for that and one of my Magisk modules may help you.

Believe me, you don't need HMA to do this, you're just bugging your Play Store for nothing.

**Comment by NFG-Hooks** [comment]
> > hmm 🤔, i don't add it to the blacklist ..i apply a blacklist on it, so those apps can't be updated anymore.
> > also it's not a known issue, since the Stable version 3.0.6 doesn't have it and every thing is working as i wanted.
> > another thing this problem only happen when i enable vold app data option from the settings
> > if i kept it off every thing going well the issue appears when enabling this option.
> 
> If you just want to prevent some of your applications from being automatically updated by the Play Store, then you don't need HMA for that. Two Xposed modules exist for that and one of my Magisk modules may help you.
> 
> Believe me, you don't need HMA to do this, you're just bugging your Play Store for nothing.

okay forgot play store 
i use HMA to hide some unwanted apps from MT Manager so when i want to extract an app the app list  loads faster but if i hide anything from MT Manager it keeps freezing the same as play store what i should do in this case 🤔?

**Comment by Dr-TSNG** [comment]
Does this happen with vold app data isolation off?

**Comment by cracky5322** [comment]
Strangely enough, my use of the HMA Blacklist for Google Play has been working fine and the app hasn't crashed

**Comment by NFG-Hooks** [comment]
> Does this happen with vold app data isolation off?

nope if vold app data isolation off every thing work fine

**Comment by BlueCat300** [comment]
> Does this happen with vold app data isolation off?

I confirm, the problem appears only when using "vold app data". The same thing happens with Galaxy Store. It looks like this will happen with all system applications.

**Comment by NFG-Hooks** [comment]
> > Does this happen with vold app data isolation off?
> 
> I confirm, the problem appears only when using "vold app data". The same thing happens with Galaxy Store. It looks like this will happen with all system applications.

Not system apps only MT Manager has the same problem never opens

**Comment by zgfg** [comment]
Confirming, with HMA v3.1.1:

1) I cannot open PlayStore (splash screen stays forever)

2) Cannot test Play Integrity (Check rotates forever, both in PI API Checker and TB-Checker)

That happens IF I ENABLE Hide for Google Play Store in App manage, and EVEN (?!) if I use 0 templates for PlayStore

However, if I disable hiding for PlayStore then PlayStore opens immediately and PI API Checker successfully tests

Also, if I revert HMA to the previous v3.1.0, then with hiding enabled for PlayStore and the corresponding template enabled (for real detaching YouTube, AndroidAuto and couple of more apps) everything is again ok

Hence a problem for me is now specifically with HMA v3.1.1

Magisk 25206, Zygisk-LSPosed
MIUI 13/Android 12

**Comment by zgfg** [comment]
> It has not been updated for more than 14d. If there is no further update, this Issue will be closed.

What should I update - I did report the problem

**Comment by NFG-Hooks** [comment]
What's up? it's long time ago... Take your time and do what it's required to solve the problem 
I I appreciate your work Thank you ❤

btw it will be nice if you made HMA identifies the xposed modules when selecting them, the same as privacy space app

**Comment by zgfg** [comment]
Retested again on the two phones (Magisk Canary and Delta), HMA 3.1.1 - still if Hide is enabled for PlayStore=com.android.vending (Blacklist mode and with a template assigned to hide eg YouTube or even without a template):

- PlayStore cannot be opened (splash triangle stays forever)
- Play Integrity API, when clicked on Check it will spin forever

I didn't have that problem with HMA v2 and I used at that time HMA to detach YT and Android Auto and couple of other apps from PlayStore.
Ie, PlayStore that way didn't show YT and AA as installed and didn't bother to update (I need that bcs I use modded YT and AA)

However, described problem started when I updated HMA to v3

As a result, I stopped using HMA for detaching from PlayStore and started to use UpdateLocker

Nevertheless, just wanted to emphasize that there was no problem with HMA v2

---

Attached logs for PlayStore and PI API Checker
OK = when Hide is not enabled for PlayStore (then PlayStore normally opens and PI API Checker successfully checks the Integrity)
NOK = when Hide is enabled for PlayStore (PlayStore does not open and PI API Checker checks forever)

![Screenshot_2023-03-10-09-49-12-854_com tsng hidemyapplist](https://user-images.githubusercontent.com/51943147/224268869-cdb1ca53-7389-42c2-a303-683dbeb5d8bb.jpg)
[com.android.vending-NOK.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/10940227/com.android.vending-NOK.zip)
[com.android.vending-OK.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/10940230/com.android.vending-OK.zip)
[gr.nikolasspyr.integritycheck-NOK.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/10940234/gr.nikolasspyr.integritycheck-NOK.zip)
[gr.nikolasspyr.integritycheck-NOK1.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/10940236/gr.nikolasspyr.integritycheck-NOK1.zip)
[gr.nikolasspyr.integritycheck.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/10940239/gr.nikolasspyr.integritycheck.zip)

**Comment by Typhonling** [comment]
> Ok, retested now with Vold Data Isolation off: PlayStore opens fine, and PI API Checker checks successfully
> 
> However, with Vold Data Isolation disabled, then Ruru detects Libc and Syscall (although for Ruru all LSPosed modules are hidden and although I also have another Data Isolation module installed)
> 
> Hence I rather enable Vold Data Isolation (per default) and do not use HMA for detaching apps from PlayStore (using UpdateLocker instead)
> 
> Then everything works as expected
> 
> See:
> 
> ## https://forum.xda-developers.com/t/hide-my-applist-a-brief-guide.4519731/post-88264113
> (Btw, the originally observed issue is maybe not a bug but the result of Vold Data Isolation enabled,)

确实存在这个问题，观察到的对Play Store启用的后果：
1、清除数据后首次打开无法运行，黑屏。首次运行后再对Play Store隐藏，可以正常运行。
2、无法更新或安装带有obb数据包的应用（大部分为游戏）。

建议：不要对Play Store进行隐藏。改用其他方式禁用对特定软件的更新。
