### ISSUE TITLE
Work Profile Apps Support [Bug] 

### ISSUE THREAD

**Issue by everclearecct** [Dr-TSNG/Hide-My-Applist#249]
### Steps to reproduce/复现步骤

1. Work Profile Apps doesn't show up in list

### Expected behaviour/预期行为

in older version (2.3.2), Work Profile Apps is in list.

### Actual behaviour/实际行为

Work Profile Apps doesn't show up in list.

### Xposed Module List/Xposed 模块列表

```Shell
HMA
```

### Magisk Module List/Magisk 模块列表

```Shell
LSPosed
Shamiko
Sui
Pixel Launcher Mods Overlay
Nano NDK
```

### Hide-My-Applist version/Hide-My-Applist 版本

3.1.0-beta.r400.f09af4b-debug

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25.2

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

[hma_logs_2022-12-31_22.10.13.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/10327474/hma_logs_2022-12-31_22.10.13.log)

**Comment by Dr-TSNG** [comment]
put the [bug] on the front
