### ISSUE TITLE
[Bug] License check / in-app-purchase doesnt work after hiding the app from Play Store

### ISSUE THREAD

**Issue by Senliast** [Dr-TSNG/Hide-My-Applist#251]
### Steps to reproduce/复现步骤

1. Hide a paid app or an app with in-app-purchase from Play Store.
2. Wait until the app tries to verify license (different by different apps) or try to make an in-app-purchase in the hidden app.

### Expected behaviour/预期行为

The app can successfully verify license and the in-app-purchase is possible.

### Actual behaviour/实际行为

The cannot verify license (message, that the license was not found) and the in-app-purchase in not possible.

### Xposed Module List/Xposed 模块列表

```Shell
Automatic advanced setfings expander
Custom Quick Setfings
Disable-Flag_secure
GravityBox [R]
Hide Emergency Button
Physical Button Master Control
SudoHide
UpdateLocker
XPrivacyLua
BluetoothToolkit (disabled)
```

### Magisk Module List/Magisk 模块列表

```Shell
ANX48MPFix R
ANXCamera
AuroraServices
BuiltInBusyBox
CustomBootAnimation
De-Bloater
F-Droid Privileged Extension
Google Sans Plus
MagiskHide Props Config
NoStorageRestrict
Rboard Themes
substratum
Zygisk - LSPosed
```

### Hide-My-Applist version/Hide-My-Applist 版本

V3.1.1.r404.c9f7cbb-debug

### Android version/Android 版本

Android 11

### Magisk version/Magisk 版本

Magisk 25.2 (25200)

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

[hma_logs_2023-01-12_21.27.21.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/10405750/hma_logs_2023-01-12_21.27.21.log)

**Comment by Dr-TSNG** [comment]
Why don't you think it is expected?

**Comment by Senliast** [comment]
@Dr-TSNG I would like to hide apps from Google Play in order to them not to be updated, as the integrated auto-update setting in Google Play often will be reset and the apps will be auto-updated. Could you maybe review your decision?

**Comment by Dr-TSNG** [comment]
Never and impossible because you could not verify something that you cannot even get access to, which is not MY decision.
