### ISSUE TITLE
[Bug] proplem with Vold app data isolatoin

### ISSUE THREAD

**Issue by DEVTE545** [Dr-TSNG/Hide-My-Applist#253]
### Steps to reproduce/复现步骤

Hello, I have a problem that I could not solve. I activated the hide on the home screen application (the system application) and hid an application and it succeeded, but I wanted to hide it from the "recent applications" that appears from the navigation bar, so I started searching in the application for something that might help me with that and I activated " Vold app data isolatoin" and then restarted the device, the lock screen appeared normally and opened the lock, and then the main screen became black and came back every second and I could not open anything so I restarted the device and when I got to the lock screen I uninstalled the application via ADB and restarted the device Once again, it worked, but there is another problem, the applications never work when I try to open them, nothing appears (the settings application only opens normally) but when I go to the recent applications from the navigation bar, the applications that I tried to open appear black (I could not take a screen shot from the mobile so I took it via ADB),
I installed the application again to try to solve the problem (I also installed it using ADB) I cannot install the applications normally, I restarted the device and the problem returned again, then I repeated the matter again (uninstalling) but when I restarted the device the arrangement of the applications changed (such as the normal arrangement upon factory reset or first use) but the problem of not running applications remained.
![screen](https://user-images.githubusercontent.com/63881594/214551273-b43aa614-094f-43f6-a76d-2fbd0eebfd39.png)

### Expected behaviour/预期行为

.

### Actual behaviour/实际行为

.

### Xposed Module List/Xposed 模块列表

```Shell
Hide My Applist
Lucky Patcher
Thanox
```

### Magisk Module List/Magisk 模块列表

```Shell
 I cannot open Magisk now
```

### Hide-My-Applist version/Hide-My-Applist 版本

V3.1.1

### Android version/Android 版本

Android 11 One UI 3.1 01/11/2022

### Magisk version/Magisk 版本

25.2-delta-6 (25200)

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

[dumpstate-2023-01-25-13-54-25.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/10498875/dumpstate-2023-01-25-13-54-25.zip)

**Comment by LynxCatTheThird** [comment]
I met this problem too. Did you fix it?

**Comment by lywsyxx** [comment]
If you can still connect via ADB, you can manually turn off Vold app data isolatoin by this command :

> adb shell setprop persist.sys.vold_app_data_isolation_enabled 0
