### ISSUE TITLE
[Bug] KernelSU has given root access to the HMA application but in Settings - Data Isolation it shows: Permission denied

### ISSUE THREAD

**Issue by yhaue** [Dr-TSNG/Hide-My-Applist#255]
### Steps to reproduce/复现步骤

1. Apply root access to HMA in KernelSu Manager(At this point HMA has been activated)
2. Open HMA, click Settings - Data Isolation - App data isolation or Vold app data isolation

### Expected behaviour/预期行为

Normally change

### Actual behaviour/实际行为

HMA prompt: permission denied

### Xposed Module List/Xposed 模块列表

```Shell
HMA3.1.1
Thanox 4.1.5
```

### Magisk Module List/Magisk 模块列表

```Shell
LSPosed 1.8.6(6839)
Zygisk On KernelSU 4-0.6.2(66)
```

### Hide-My-Applist version/Hide-My-Applist 版本

3.1.1

### Android version/Android 版本

13

### Magisk version/Magisk 版本

KSU:10677 Manager:v0.4.0(10672)

### Version requirement/版本要求

Public release/beta version/公开发布/测试版

### Logs/日志

[hma_logs_2023-02-28_22.45.59.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/10890688/hma_logs_2023-02-28_22.45.59.log)

But I think the log is useless.

**Comment by Dr-TSNG** [comment]
This issue is from upstream library, should wait for its update.
