### ISSUE TITLE
[Bug] Not hiding Xposed modules and Magisk app

### ISSUE THREAD

**Issue by fxckyaall** [Dr-TSNG/Hide-My-Applist#258]
### Steps to reproduce/复现步骤

1. 添加隐藏目标到黑名单模板中的不可见列表
2. 给应用设置模板

### Expected behaviour/预期行为

Applist Detector检测全部通过

### Actual behaviour/实际行为

经过Applist Detector检测，Xposed modules和Magisk app被发现
![photo_2023-03-22_15-00-54](https://user-images.githubusercontent.com/108215379/226826105-a3b91011-bf44-4380-b320-6343a60003cc.jpg)

### Xposed Module List/Xposed 模块列表

```Shell
剪贴板过滤器
懂球帝
fcmfix
LuckyTool
隐藏应用列表
YouTube AdAway
```

### Magisk Module List/Magisk 模块列表

```Shell
oqm.ucl
```

### Hide-My-Applist version/Hide-My-Applist 版本

V3.1.1-r404.c9f7cbb

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25.2

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

[LSPosed_2023-03-22T15_06_46.650537.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/11037297/LSPosed_2023-03-22T15_06_46.650537.zip)

**Comment by cracky5322** [comment]
@fxckyaall 備份你的設定後上傳上來

**Comment by fxckyaall** [comment]
> @fxckyaall 备份你的设定后上传上来

[HMA_Config (2).zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/11071532/HMA_Config.2.zip)

**Comment by cracky5322** [comment]
@fxckyaall 你根本沒有對測試器啟用隱藏
