### ISSUE TITLE
[Bug] 在酷派手机上无法隐藏(同系统版本其他厂商的手机可以隐藏)

### ISSUE THREAD

**Issue by java02014** [Dr-TSNG/Hide-My-Applist#268]
### Steps to reproduce/复现步骤

必现

### Expected behaviour/预期行为

可以正常隐藏

### Actual behaviour/实际行为

无法隐藏

### Xposed Module List/Xposed 模块列表

```Shell
Hide-My-Applist
```

### Magisk Module List/Magisk 模块列表

```Shell
Shamiko
Zygisk-LSPosed
```

### Hide-My-Applist version/Hide-My-Applist 版本

3.1.1

### Android version/Android 版本

Android 11

### Magisk version/Magisk 版本

25.2

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

[hma_logs_2023-06-21_16.14.53.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/11815342/hma_logs_2023-06-21_16.14.53.log)

**Comment by asuradoll** [comment]
same issues
