### ISSUE TITLE
[Feature request] Apply multi templates for selected apps

### ISSUE THREAD

**Issue by lelemka0** [Dr-TSNG/Hide-My-Applist#27]
Hope to add features to allow to apply multi templates for selected apps.
This can be more convenient to manage templates and reduce duplicate templates.

**Comment by Dr-TSNG** [comment]
There is a question that multi templates may cause conflicts and a lot of complexity, for example:
E1: If one template applies interception A for app S, and another template applies interception B for app S, it's hard to deal with this in backend.
E2: If one template uses whitelist and another uses blacklist, there will be a totally confusion within the backend.

**Comment by lelemka0** [comment]
Templates that use different modes should not be mixed, or warn users when they are mixed.
I tried to write a multi-template implementation. Choose a main template and add the application list of other templates only.
https://github.com/lelemka0/Hide-My-Applist/tree/multitpl
I don't know how to adjust the ui, so the code is also untested. If you have time, please check.

**Comment by Dr-TSNG** [comment]
Completed officially.

**Comment by Dr-TSNG** [comment]
Completed officially.
