### ISSUE TITLE
[Bug] HMA and all activated apps crashes if Enforce SuList in magisk is enabled.

### ISSUE THREAD

**Issue by Naguz** [Dr-TSNG/Hide-My-Applist#280]
### Steps to reproduce/复现步骤

With lates Magisk Delta (26.1 stable) and latest  Lsposed 1.9.1. (6990) latest Hide My Applist (3.2) does not work if I set Enforce SuList in Magisk. Adding Hide My Applist to the SuList does no help, even with a reboot and force close/clear cache of hide my app list. 

HMA does not open, but freezes on the opening screen. The apps that are enabled in HMA refuses to work, either freezing on start or crashing while running. 

After disabling SuList in magisk, stuff works again.

1: Enable "Enforce SuList" in Magisk
2: Reboot
3: HMA no longer works, and neither does any app HMA is enabled for.

### Expected behaviour/预期行为

HMA continuing to work even if Enforce SuList is enabled in Magisk

### Actual behaviour/实际行为

HMA crashes if Enforce SuList is set in magisk Delta

### Xposed Module List/Xposed 模块列表

```Shell
Only HMA installed
```

### Magisk Module List/Magisk 模块列表

```Shell
LSPosed v 1.9.1
Universal SafetyNetFix 2.4 Displax mod
```

### Hide-My-Applist version/Hide-My-Applist 版本

3.2

### Android version/Android 版本

13

### Magisk version/Magisk 版本

Magisk Delta 2.6.1 (stable branch)

### Version requirement/版本要求

Public release/beta version/公开发布/测试版

### Logs/日志

No logs from HMA available as the app crashes.

**Comment by Naguz** [comment]
There is no debug version available by the link posted i the issue form OR on the release download page, so automatically closing a bug for not using a non-available debug version seems a little counter-productive.

**Comment by pndwal** [comment]
Try to follow instructions to use CI debug build from actions?...
