### ISSUE TITLE
[Bug] There is no debug version avalable, and so it is impossible to file bugs that are not automatically invalidated

### ISSUE THREAD

**Issue by Naguz** [Dr-TSNG/Hide-My-Applist#281]
### Steps to reproduce/复现步骤

1. Try to file a bug
2. It is impossible to get a debug version for version 3.2, the link in the issue form is invalid. The latest version is HMA-V3.1.1.r404.c9f7cbb-debug, which is expired ie. not possible to download.
3. 3. The bug is automatically invalidated

### Expected behaviour/预期行为

Don't put unreasonable  restrictions on your issue form, and CERTAINLY don't do so if they are  impossible to fullfill 

### Actual behaviour/实际行为

Bug filing impossible.

### Xposed Module List/Xposed 模块列表

```Shell
N/A
```

### Magisk Module List/Magisk 模块列表

```Shell
N/A
```

### Hide-My-Applist version/Hide-My-Applist 版本

HMA-V3.1.1.r404.c9f7cbb-debug

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.1

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

N/A

**Comment by cracky5322** [comment]
You also did not provide relevant logs
