### ISSUE TITLE
1.6.1.Native闪退

### ISSUE THREAD

**Issue by Trustedinstall** [Dr-TSNG/Hide-My-Applist#29]
OnePlus 3T
ROM: Mokee Android 9
Magisk: 23
Riru: 25.4.4.r426.05efc94
EdXposed: 0.5.2.1_4677 (YAHFA)
1.5.4.Native一切正常,更新到1.6.1.Native点开应用就闪退
[logcat_05-21-2021_12-10-07.txt](https://github.com/Dr-TSNG/Hide-My-Applist/files/6520033/logcat_05-21-2021_12-10-07.txt)

**Comment by Dr-TSNG** [comment]
尝试最新版+riru模块
