### ISSUE TITLE
对系统应用隐藏特定应用

### ISSUE THREAD

**Issue by chunxiaoyi** [Dr-TSNG/Hide-My-Applist#3]
这个模块似乎不能对系统应用隐藏应用？

主要的需求是 Google Play 商店会无差别检查更新，甚至连忽略某个 app 的更新都做不到，只能暂停自动更新然后整天横在上面很烦

我不想让 Google 检测 YouTube 的更新，因为装了 YouTube Vanced，这个去广告的版本落后于官方版本 YouTube，所以会一直提示更新，只能用单独 hide YouTube 包名的办法变相做到让 play 不要检测更新

但是这个 app 无法对 system app （即 Google play）隐藏特定的某一应用，以后会在未来添加支持吗？

**Comment by Dr-TSNG** [comment]
并不是不能实现对系统app隐藏，而是当初出于两个原因没有写进去，一个是系统程序经常是时不时就在读应用列表，每次都要读一次配置文件会让手机非常卡（现在已经解决），二个就是还没做搜索框，导致如果把系统app加进去列表就太长了很影响体验，现在是先把搜索框做完再开放对系统应用隐藏

**Comment by chunxiaoyi** [comment]
谢谢，另外关于列表太长的问题，个人建议默认不显示对系统应用隐藏，可以在右上角加个小开关自行给有需求的人开启

**Comment by Dr-TSNG** [comment]
是打算这么做的

**Comment by chunxiaoyi** [comment]
好的，非常感谢

**Comment by Imamfachrudin** [comment]
嗨，先生，如何完美地使用隱藏我的 applist 模塊。

步驟是什麼

我真的很想使用這個模塊

**Comment by Imamfachrudin** [comment]
嗨，先生，如何完美地使用隱藏我的 applist 模塊。

步驟是什麼

我真的很想使用這個模塊

**Comment by Imamfachrudin** [comment]
嗨，先生，如何使用隱藏我的 applist 模塊？

**Comment by cracky5322** [comment]
> 這個模塊似乎不能對系統應用隱藏應用？
> 
> 主要的需求是 Google Play 商店會無航空檢查更新，甚至連某個 app 的更新都不到，可以暫停自動更新然後橫向在很煩
> 
> 我不想讓檢測YouTube的更新，因為裝了YouTube，這個去廣告的單一版本於官方版本的YouTube，所以會一直提示更新，只能隱藏YouTube包名的方法變相工具讓玩不要檢測更新
> 
> 但是應用無法對系統應用（即 Google play）隱藏特定的這個應用，以後會在未來添加嗎？

https://github.com/Magisk-Modules-Repo/Detach

**Comment by Aritro37** [comment]
@cracky5322 誰告訴你不能對系統程式隱藏的？右上角三個點那麼大的顯示系統應用看不見么

**Comment by cracky5322** [comment]
> @cracky5322 誰告訴你不能對系統程式隱藏的？右上角三個點那麼大的顯示系統應用看不見么

我有說不能對系統隱藏嗎...你腦袋抽風?還是需要看眼科?
