### ISSUE TITLE
Device can't boot or LSPosed EdXposed not installed - from version 1.3.2 and onwards

### ISSUE THREAD

**Issue by jh0bc** [Dr-TSNG/Hide-My-Applist#4]
I have a Mi 9T Pro on MIUI EU 21.4.14 with latest Magisk Canary and LSPosed.

After the update to version 1.3.2 my device sometimes can't boot or when it boots LSPosed says i'ts not installed.

Tried with EdXposed and the same happen.

Everything went back to normal after removing your module (device can boot and Xposed installation status is back to "Installed")

With version 1.3.1 beta this issue doesn't happen

**Comment by Dr-TSNG** [comment]
Can you provide boot logs? I'll try to locate the bug.

**Comment by jh0bc** [comment]
Sure!

Here's a logcat right after a reboot to activate your module (1.4 beta)

[2021-04-18-18-03-32.txt](https://github.com/Dr-TSNG/Hide-My-Applist/files/6332209/2021-04-18-18-03-32.txt)

LSPosed status is "Not Installed" and at your app the status is "Module Not Activated - System service not running"

Before the reboot I enabled your module just to "System Framework"

**Comment by Dr-TSNG** [comment]
This seems not to be the boot log. I need logs when system boot to locate the problem. Maybe you should use magisk module "Log Catcher" or connect the phone to your computer and use Android Studio to get the logcat.

**Comment by lelemka0** [comment]
I am also running MIUI EU on my device and encountered the same problem.
Since the work mode has changed to system hook, the problem has always existed.

**Comment by lelemka0** [comment]
The boot log about xposed is as follows
[LSPosed.boot.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/6337885/LSPosed.boot.log)

May be the key part

> 04-20 01:05:36.344  3339  3339 E LSPosed-Bridge: java.lang.NullPointerException: lpp.appInfo must not be null
04-20 01:05:36.344  3339  3339 E LSPosed-Bridge: 	at com.tsng.hidemyapplist.xposed.hooks.IndividualHooks.handleLoadPackage(IndividualHooks.kt:13)
04-20 01:05:36.344  3339  3339 E LSPosed-Bridge: 	at com.tsng.hidemyapplist.xposed.XposedEntry.handleLoadPackage(XposedEntry.kt:21)
04-20 01:05:36.344  3339  3339 E LSPosed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
04-20 01:05:36.344  3339  3339 E LSPosed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
04-20 01:05:36.344  3339  3339 E LSPosed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
04-20 01:05:36.344  3339  3339 E LSPosed-Bridge: 	at X0.beforeHookedMethod(:1)
04-20 01:05:36.344  3339  3339 E LSPosed-Bridge: 	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
04-20 01:05:36.344  3339  3339 E LSPosed-Bridge: 	at LspHooker_.startBootstrapServices(Unknown Source:11)
04-20 01:05:36.344  3339  3339 E LSPosed-Bridge: 	at com.android.server.SystemServer.run(Unknown Source:417)
04-20 01:05:36.344  3339  3339 E LSPosed-Bridge: 	at com.android.server.SystemServer.main(Unknown Source:10)
04-20 01:05:36.344  3339  3339 E LSPosed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 01:05:36.344  3339  3339 E LSPosed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
04-20 01:05:36.344  3339  3339 E LSPosed-Bridge: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:285)
04-20 01:05:51.576  3339  3339 I LSPosed-Bridge: [HMA LOG] [INFO] System hook installed
04-20 01:05:51.577  3339  3441 I LSPosed-Bridge: [HMA LOG] [INFO] Waiting for preference provider
04-20 01:05:51.912   890  1465 W LSPosedService: system restarted...
04-20 01:05:51.916  3339  3363 I LSPosed : registered package receiver
04-20 01:05:51.917  3339  3363 I LSPosed : registered package receiver
04-20 01:05:51.917  3339  3363 I LSPosedService: binder received
04-20 01:05:51.917   890  1465 I LSPosedService: sent service to bridge
04-20 01:06:26.061  3339  3434 I SystemServerTimingAsync: InitThreadPoolExec:Update app-ops uidState in case package org.lsposed.manager changed
04-20 01:06:27.269   890  1465 I LSPosedService: service activity is dead. 
04-20 01:06:27.269   890  1465 I LSPosedService: clear ServiceManager
04-20 01:06:27.269   890  1465 W LSPosedService: system server died
04-20 01:06:46.281   890  1465 W LSPosedService: system restarted...
04-20 01:06:46.282   890  1465 W LSPosedService: no response from bridge, retry in 1s
04-20 01:06:47.282   890  1465 W LSPosedService: no response from bridge, retry in 1s
04-20 01:06:48.282   890  1465 W LSPosedService: no response from bridge, retry in 1s
04-20 01:06:49.283   890  1465 W LSPosedService: no response from bridge

**Comment by lelemka0** [comment]
> 04-20 01:05:57.612  3339  3441 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:0 com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$afterHookedMethod$1.invoke:163 com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$afterHookedMethod$1.invoke:26 kotlin.concurrent.ThreadsKt$thread$thread$1.run:30 <bottom of call stack> 
04-20 01:05:59.641  3339  3367 W system_server: ContentStack with tid 3441, wait time: 502ms, monitor id: 29584
04-20 01:05:59.641  3339  3367 W system_server: PerfMonitor owner thread(3441) stack is:
04-20 01:05:59.641  3339  3367 W system_server:   at com.android.server.pm.PackageManagerService.getInstantAppPackageName(PackageManagerService.java:-1)
04-20 01:05:59.641  3339  3367 W system_server:   - waiting to lock <0x00ab5982> (a java.lang.Object) held by thread 1
04-20 01:05:59.641  3339  3367 W system_server:   at com.android.server.pm.PackageManagerService.updateFlagsForResolve(PackageManagerService.java:-1)
04-20 01:05:59.641  3339  3367 W system_server:   at com.android.server.pm.PackageManagerService.updateFlagsForResolve(PackageManagerService.java:-1)
04-20 01:05:59.641  3339  3367 W system_server:   at com.android.server.pm.PackageManagerService.resolveServiceInternal(PackageManagerService.java:-1)
04-20 01:05:59.641  3339  3367 W system_server:   at com.android.server.pm.PackageManagerService.access$8600(PackageManagerService.java:-1)
04-20 01:05:59.641  3339  3367 W system_server:   at com.android.server.pm.PackageManagerService$PackageManagerInternalImpl.resolveService(PackageManagerService.java:-1)
04-20 01:05:59.641  3339  3367 W system_server:   at com.android.server.am.ActiveServices.retrieveServiceLocked(ActiveServices.java:-1)
04-20 01:05:59.641  3339  3367 W system_server:   at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:-1)
04-20 01:05:59.641  3339  3367 W system_server:   at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:-1)
04-20 01:05:59.641  3339  3367 W system_server:   at com.android.server.am.ActivityManagerService.startService(ActivityManagerService.java:-1)
04-20 01:05:59.641  3339  3367 W system_server:   - locked <0x03aa2c45> (a com.android.server.am.ActivityManagerService)
04-20 01:05:59.641  3339  3367 W system_server:   at android.app.ContextImpl.startServiceCommon(ContextImpl.java:-1)
04-20 01:05:59.641  3339  3367 W system_server:   at android.app.ContextImpl.startService(ContextImpl.java:-1)
04-20 01:05:59.641  3339  3367 W system_server:   at com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$afterHookedMethod$1.invoke(PackageManagerService.kt:163)
04-20 01:05:59.641  3339  3367 W system_server:   at com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$afterHookedMethod$1.invoke(PackageManagerService.kt:26)
04-20 01:05:59.641  3339  3367 W system_server:   at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by Dr-TSNG** [comment]
Unfortunately, there are just few native logs which can provide little information, so more procedures are needed. Please try these two apks and find if lsposed shows "installed".
[download here](https://github.com/Dr-TSNG/Hide-My-Applist/releases/tag/DEBUG)

**Comment by lelemka0** [comment]
These two apks seem to have the same phenomenon.
Lsposed shows "installed" and Hide-My-Applist shows "Module Activated" and "System service not running".
There also seems to be few change in the log except for the following line.

> LSPosed-Bridge: [HMA LOG] [ERROR] callServiceIsUseHook: Service not found

**Comment by Dr-TSNG** [comment]
Changes hook entry in 1.4.1, please try if it works.

**Comment by jh0bc** [comment]
Here's the logs of debug apk's and the new 1.4.1, with the latest one the device can't even boot. 

I also attached generated logs of LSPosed when using the debugs apk's.

With both debug apk's the LSPosed status is "Installed" but your module is "System service not running"

[logs.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/6343872/logs.zip)

**Comment by Dr-TSNG** [comment]
Maybe MIUI eu changed some system code strangely, I'll try to locate them these days.

**Comment by Dr-TSNG** [comment]
Please try these apks and catch logs. Maybe I've found one of the bugs.
[debug.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/6376015/debug.zip)

**Comment by jh0bc** [comment]
Here's the logs:

[logs.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/6385933/logs.zip)

With Debug 1 the device can't boot (stuck at MIUI logo)

Debug 2 take a little bit but booted but right after that the screen went to dark and the device hanged

**Comment by Dr-TSNG** [comment]
What about this version
[app-debug.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/6404128/app-debug.zip)

**Comment by lelemka0** [comment]
> What about this version
> [app-debug.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/6404128/app-debug.zip)

This version seems to work fine on my Mi9TPro with MIUI EU 21.4.29.

**Comment by Dr-TSNG** [comment]
OK, please try the latest release. Hope there is no problem

**Comment by lelemka0** [comment]
I tried the latest version with native hook, booted and running normally.
But I found the file detections method not work, include java and native.

**Comment by Dr-TSNG** [comment]
OK, please provide Android logs when finish running a detection test.

**Comment by lelemka0** [comment]
On version 1.5.1, this problem no longer exists.
Thanks for your work.

**Comment by jh0bc** [comment]
> What about this version
> [app-debug.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/6404128/app-debug.zip)

This version and the 1.5.1 is working fine on latest MIUI EU Weekly (21.4.29)

Thanks a lot! :)

Here's some logs:

[logs.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/6430043/logs.zip)

**Comment by Dr-TSNG** [comment]
Problem solved
