### ISSUE TITLE
【BUG反馈】插件提示未安装

### ISSUE THREAD

**Issue by achooyu** [Dr-TSNG/Hide-My-Applist#45]
1、不管有没有装插件都显示未安装，1.6.6和1.6.5版本都这样，用的3.0的插件
2、模块激活后，装不装插件都能够隐藏，除了“File detections”显示“F”。
3、这个软件我的手机不能转成系统应用，一转就“系统未运行”，本次没有抓这个包，抓的是常规安装下的bug

辛苦了！！！

![1](https://user-images.githubusercontent.com/25449326/120189005-66ead800-c249-11eb-8b72-5358e24c5abf.jpg)
![微信图片_20210531194840](https://user-images.githubusercontent.com/25449326/120188920-4b7fcd00-c249-11eb-8d1a-5e5ad6c15906.jpg)
![微信图片_20210531194836](https://user-images.githubusercontent.com/25449326/120188891-41f66500-c249-11eb-9b6a-6c008b433089.jpg)
![微信图片_20210531194605](https://user-images.githubusercontent.com/25449326/120188639-f17f0780-c248-11eb-918b-ce9e4e636d6d.jpg)
![微信图片_20210531194600](https://user-images.githubusercontent.com/25449326/120188675-fa6fd900-c248-11eb-96d1-33a7af4f6626.jpg)
[EdXposed_Modules_20210531_191209.txt](https://github.com/Dr-TSNG/Hide-My-Applist/files/6569991/EdXposed_Modules_20210531_191209.txt)
[EdXposed_Verbose_20210531_191202.txt](https://github.com/Dr-TSNG/Hide-My-Applist/files/6569994/EdXposed_Verbose_20210531_191202.txt)
[hma_logs_05-31_19-06-31.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/6569995/hma_logs_05-31_19-06-31.log)
[magisk-share_img_tmp_1.txt](https://github.com/Dr-TSNG/Hide-My-Applist/files/6570037/magisk-share_img_tmp_1.txt)

**Comment by chunxiaoyi** [comment]
不是，你转换成系统应用意义何在？

**Comment by XGMO9** [comment]
@achooyu 1.升级你的 magisk 先
2.你的截图中并没看到 riru-hidemyapplist，何来文件拦截能力
3.两个版本 edxp 搁这儿养蛊呢

**Comment by kaniwow** [comment]
@achooyu 1.升级你的 magisk 先
2.你的截图中并没看到 riru-hidemyapplist，何来文件拦截能力
3.两个版本 edxp 搁这儿养蛊呢

**Comment by Dr-TSNG** [comment]
4. 不懂你为啥要转系统应用，这是非常蠢的做法
5. 低质问题

**Comment by achooyu** [comment]
> @achooyu1.古力马吉斯克
> 2.古力特克·特里克特·里鲁-希德米应用程序，准准吉亚
> 克·比奇3.埃奇·里特克斯·德·特里克特·吉特·特里克·吉普·特维利特·吉普

虽然没截图 但实际上是安装了  其次如果能升级magisk我早就升级了。
