### ISSUE TITLE
使用riru插件后仍然能进行file detections检测

### ISSUE THREAD

**Issue by lxd301491** [Dr-TSNG/Hide-My-Applist#47]
![Screenshot_20210606-165122.jpg](https://user-images.githubusercontent.com/18732479/120918527-73f34580-c6e7-11eb-8f7a-d2491625ac5f.jpg)![Screenshot_20210606-165115.jpg](https://user-images.githubusercontent.com/18732479/120918533-79e92680-c6e7-11eb-8e61-aff768ab4190.jpg)
手机环境
一加五t  
android p
h2os

**Comment by lxd301491** [comment]
![Screenshot_20210606-165122.jpg](https://user-images.githubusercontent.com/18732479/120918734-802bd280-c6e8-11eb-9ad6-b3b82d6ce7f7.jpg)

**Comment by lxd301491** [comment]
![Screenshot_20210606-165948.jpg](https://user-images.githubusercontent.com/18732479/120918757-9c2f7400-c6e8-11eb-9ed6-eb25fd8298f1.jpg)

**Comment by byxiaorun** [comment]
@lxd301491 此次更新后端较前版变化较大，更新后请手动执行一遍 设置 - 停止系统服务 - 同时清理环境
下次记得看更新日志
