### ISSUE TITLE
系统服务未运行

### ISSUE THREAD

**Issue by qifeng2233** [Dr-TSNG/Hide-My-Applist#49]
v1.7 beta(riru模块v0.3.6) Android10提示系统服务未运行

**Comment by Dr-TSNG** [comment]
再三强调切忌只更新 app 不更新 riru 插件，你就是硬不更新，那我也没任何办法

**Comment by qifeng2233** [comment]
> 再三强调切忌只更新 app 不更新 riru 插件，你就是硬不更新，那我也没任何办法

我没有更新riru插件

**Comment by Dr-TSNG** [comment]
请百度一下切忌这个词的意思

**Comment by qifeng2233** [comment]
> 请百度一下切忌这个词的意思

是我喝高了(●—●)
