### ISSUE TITLE
File detections 检测不通过

### ISSUE THREAD

**Issue by Flammulinavelutipes** [Dr-TSNG/Hide-My-Applist#5]
按照app内教程开启检测，其他都没问题，就File detections最后一项显示F，是哪个地方还需要设置一下吗？

![Screenshot_20210417035115](https://user-images.githubusercontent.com/26811405/115077181-3583aa80-9f30-11eb-97de-e85c34a20e45.png)

![Screenshot_20210417035202](https://user-images.githubusercontent.com/26811405/115077247-4b916b00-9f30-11eb-8521-3ebed28ce292.png)

**Comment by Dr-TSNG** [comment]
因为mative拦截本来就还没写
