### ISSUE TITLE
可否能在一个“生效应用”上选择多个模板？

### ISSUE THREAD

**Issue by KsharpMoring** [Dr-TSNG/Hide-My-Applist#50]
如题。

为了避免冲突，在同一 “生效应用” 选择的多个模板内，要隐藏的应用不可以有重合。
比如模板1隐藏A、B应用；模板2隐藏C、D应用；模板3隐藏A、C应用。
则此时在一个“生效应用”上可以同时选择选择模板1和模板2（因为没有重合）；
而模板1和模板3就不能在一个上 “生效应用” 同时选择（因为A重合了）。

**Comment by byxiaorun** [comment]
@KsharpMoring 还要判断模版是否重合的话，太麻烦了，而且还要考虑白+黒这种情况，限制用户反而麻烦，而且没写好会引发bug，与其这样子还不如上单个软件独立配置
