### ISSUE TITLE
隐藏所有Xp模块会导致部分功能异常？是bug吗？

### ISSUE THREAD

**Issue by EatmeIon** [Dr-TSNG/Hide-My-Applist#51]
如题
我创建了一个隐藏所有xp模块、root、和使用root的应用模板
目前发现
对京东金融启用，首页启动图无法跳过！其它的暂未发现问题！（爱看影视的反检测vpn正常）
对支付宝启用，会导致XQ_Crystal一直显示小号模式不工作
上帝模式无法编辑（测试多个App都这样，之前标记的可以正常生效）

不知道是bug还是正常现象
Android9；MIUI11；LSPosed1455767；Magisk23.0；Riru2544；隐藏应用列表1.7/0411

**Comment by byxiaorun** [comment]
@EatmeIon 1. 京东金融这个问题可能是由已知 bug 导致的
2. 所有用到 pm 和 XSharedPreferences 的模块必然出问题，因为会被拦截。自己联系那些模块作者修改或者不要对他们开启隐藏

**Comment by EatmeIon** [comment]
> @EatmeIon 1. 京东金融这个问题可能是由已知 bug 导致的
> 2. 所有用到 pm 和 XSharedPreferences 的模块必然出问题，因为会被拦截。自己联系那些模块作者修改或者不要对他们开启隐藏

好吧，看来只能酱紫了
京东金融那个是用到了对话框取消的自动电击按钮，会自动点击启动广告下面的跳过按钮

**Comment by Dr-TSNG** [comment]
@EatmeIon 我理解错了，以为你是说京东金融手动点击跳过也不行。那这还是 XSharedPreference 的问题，你可以尝试不对它启用文件拦截

**Comment by EatmeIon** [comment]
> @EatmeIon 1. 京东金融这个问题可能是由已知 bug 导致的
> 2. 所有用到 pm 和 XSharedPreferences 的模块必然出问题，因为会被拦截。自己联系那些模块作者修改或者不要对他们开启隐藏

还有
Xposed模块有必要隐藏吗，如果没必要我就不隐藏了
另外，能不能加一个复制模板的功能，同一个模板复制多个，然后只需要在不同的模板里取消几个不需要隐藏的就行了
现在这个每一个模板都需要重新选属实有点不那么方便

**Comment by Dr-TSNG** [comment]
@EatmeIon 1. 一般来说没必要藏，很少有应用特地检测这个。不过有个别国产 app 会扫 maps 来得知你有没有对他启用模块
2. 在计划列表，不过 todolist 很长，不知道什么时候有时间写

**Comment by EatmeIon** [comment]
> @EatmeIon 1. 一般来说没必要藏，很少有应用特地检测这个。不过有个别国产 app 会扫 maps 来得知你有没有对他启用模块
> 2. 在计划列表，不过 todolist 很长，不知道什么时候有时间写

maps不是地图吗？

**Comment by Dr-TSNG** [comment]
@EatmeIon 请自行百度 maps 是什么。。

**Comment by Aritro37** [comment]
@EatmeIon 是的就是地图 你真聪明

**Comment by EatmeIon** [comment]
> @EatmeIon 请自行百度 maps 是什么。。

对王者荣耀隐藏后在进入大厅后会强退
电信营业厅闪退
无论隐藏的是啥，只要启用隐藏都酱紫
