### ISSUE TITLE
有个想法，能不能做到文件隐藏？

### ISSUE THREAD

**Issue by soulpursuit** [Dr-TSNG/Hide-My-Applist#55]
昨天在用微信的时候，突然有个想法，不知道有没有办法实现对文件进行屏蔽，没必要让微信读取到那么多的路劲，没必要点开相册的时候，就加载整个存储器所有地方的照片？

**Comment by Dr-TSNG** [comment]
出门右转存储重定向

**Comment by soulpursuit** [comment]
> 出门右转存储重定向

这个我有在用，但是它只是重定向问，而是对于微信这么大体量的，我不太敢用😂

它是重定向，我的意思是，屏蔽指定路劲或者只能访问指定路径

**Comment by Aritro37** [comment]
@soulpursuit 都说了 出门右转重定向

**Comment by cracky5322** [comment]
@soulpursuit 設定>行為>可訪問資料夾模板

**Comment by soulpursuit** [comment]
> @soulpursuit 都说了 出门右转重定向

求链接甩我脸上😂

**Comment by cracky5322** [comment]
@soulpursuit 你不是說你有用嗎...？

**Comment by soulpursuit** [comment]
> @soulpursuit 設定>行為>可訪問資料夾模板
我有用这个，几个APP都开了，唯独，没有开微信，担心有时出错导致聊天记录混乱，也担心有时出现状况，紧急的时候找不到文件之类，或者运行不正常。

所以，在想，我们这个模块，我看到有 文件屏蔽，就来问问😂

**Comment by Aritro37** [comment]
@soulpursuit 建议回锁
