### ISSUE TITLE
隐藏方式选择File detections后会影响其它XP模块

### ISSUE THREAD

**Issue by etjson** [Dr-TSNG/Hide-My-Applist#62]
如题，选择后会使lataclysm模块、应用伪装、这些类似的模块失效，关闭File detections后恢复正常。

**Comment by Aritro37** [comment]
@etjson 那些模塊可能將數據存放在模塊私有目錄之類的，找那些模塊反饋去

**Comment by Dr-TSNG** [comment]
@Aritro37 为什么总有人问这种问题？自己去了解下 SharedPreferences 的原理，别啥事怪到 HMA 头上

**Comment by Aritro37** [comment]
@Dr-TSNG 因為總有些人自以為是
