### ISSUE TITLE
更新啦

### ISSUE THREAD

**Issue by EatmeIon** [Dr-TSNG/Hide-My-Applist#63]
新版本应用列表名字下面显示包名了，是否考虑改回之前的模板名？或者加个设置？

黑名单隐藏模板内的应用
白名单隐藏模板外的应用？
是否考虑能在启用黑名单时隐藏掉白名单选项？或者在设置中加个总开关选择启用黑名单或者白名单？

模板那里会显示多少App启用了该模板，是否能够添加一个点击之后可以看到哪些App启用了该模板

**Comment by Dr-TSNG** [comment]
黑白名单的图标是不一样的，点进去后黑名单会显示选择隐藏的应用，白名单会显示可见的应用，这样不会混淆
点击之后可以看到哪些App启用了该模板在todolist，不过最近我挺忙的，没什么时间写
