### ISSUE TITLE
map scan独立控制

### ISSUE THREAD

**Issue by vivian8421** [Dr-TSNG/Hide-My-Applist#66]
升级最新版 导入过去的规则 会将默认的全部隐藏方式导入 并默认开启map scan 但目前大部分bank的软件(Example:ccb,icbc,cmb....)会出现闪退,卡第一屏现象,部分软件(Example:chrome....)会出现报错等提示 可否将map scan独立出来一个选项 以此来兼容可能出现的闪退bug  同时 手动修改配置时返回不会有弹窗警告没有保存 可能导致修改未保存直接退出

**Comment by LikeJson** [comment]
@vivian8421

**Comment by LikeJson** [comment]
@vivian8421 
![image](https://user-images.githubusercontent.com/85022954/126416728-e5ee2d8f-9dce-47ef-bd99-ad150479b3ab.png)
？这里不是有吗,取消勾选就行

**Comment by vivian8421** [comment]
> 
> 
> @vivian8421
> ![image](https://user-images.githubusercontent.com/85022954/126416728-e5ee2d8f-9dce-47ef-bd99-ad150479b3ab.png)
> ？这里不是有吗,取消勾选就行

en but 我必须一个一个修改 或者将配置给其他应用  希望选择模板有这个选项
