### ISSUE TITLE
关于2.0版本的几个用户体验方面的想法

### ISSUE THREAD

**Issue by soulpursuit** [Dr-TSNG/Hide-My-Applist#67]
1、选择生效应用列表，希望可以像原来的版本一样，能显示已经开启了什么模板

2、选择生效应用列表，希望可以筛选没有开启隐藏的APP，或者可以按模板筛选已隐藏APP

3、如果可以的话，希望增加APP分类功能，在选择应用时，可以针对一类APP使用模板

4、选择生效应用，进入配置，习惯性的直接按返回，结果发现辛辛苦苦改的额外应用和配置不见了，能不能按返回的时候加个对话框？

5、模板，希望可以包含隐藏方式，在APP界面则是单独设置

**Comment by Aritro37** [comment]
@soulpursuit 这么多要求 你自己提pr

**Comment by soulpursuit** [comment]
> @soulpursuit 这么多要求 你自己提pr

只是说说想法而已，作者自己自然会筛选
