### ISSUE TITLE
color os不能再生效应用中显示安全中心～

### ISSUE THREAD

**Issue by sjkhsl** [Dr-TSNG/Hide-My-Applist#7]
想给安全中心隐藏应用，可是生效应用列表中没有～～

**Comment by Dr-TSNG** [comment]
系统应用隐藏在搜索框做出来后再加进去，最近版本主要是修bug，等bug修完再加

**Comment by sjkhsl** [comment]
> 系统应用隐藏在搜索框做出来后再加进去，最近版本主要是修bug，等

大佬，辛苦了～
