### ISSUE TITLE
上海人设app 还是能检测到root

### ISSUE THREAD

**Issue by trialman** [Dr-TSNG/Hide-My-Applist#77]
配合magiskhide也没用

http://app.rsj.sh.gov.cn/

![Screenshot_20210830-212706](https://user-images.githubusercontent.com/5611750/131365017-fdc341a7-5292-44b5-a524-a266b4868ecd.jpg)

**Comment by kaniwow** [comment]
@trialman 隐藏 root 不是 hma 的职责
