### ISSUE TITLE
已激活模块，系统服务未运行

### ISSUE THREAD

**Issue by POEG1726** [Dr-TSNG/Hide-My-Applist#78]
已激活模块，系统服务未运行

**Comment by Dr-TSNG** [comment]
日志截图复现方式是否重启过都没说，靠算命找问题吗？

**Comment by 96998a** [comment]
![Screenshot_2021-09-02-13-55-44-486_com tsng hidemyapplist](https://user-images.githubusercontent.com/21967105/131789887-5f60f90c-32e2-497e-8e24-5a6eeb61578f.jpg)
![Screenshot_2021-09-02-13-59-25-621_k btrg](https://user-images.githubusercontent.com/21967105/131790083-0d8f396a-6373-4ce0-b23d-7ccfa4821477.jpg)

已激活模块，系统服务未运行(截图：由于系统服务未运行，连日志也打不开)
面具最新版本，riui也是最新版

**Comment by 96998a** [comment]
![Uploading Screenshot_2021-09-02-14-01-23-504_me.weishu.exp.jpg…]()

用的太极·阳模式。太极里面已经激活

**Comment by 96998a** [comment]
本来没有edxposed的，是因为太极激活后系统服务未运行，没办法，才安装Edxposed试一下的，结果还是不行😂

**Comment by Fe3O4-Git** [comment]
@96998a 先关掉太极试试

**Comment by Dr-TSNG** [comment]
把太极和ed都关了，用lsp激活，发log

**Comment by 96998a** [comment]
(![Screenshot_2021-09-02-14-14-29-108_me weishu exp](https://user-images.githubusercontent.com/21967105/131792369-3ccdcbc7-2ba4-4f24-895f-25b138f8cd98.jpg)
![Screenshot_2021-09-02-14-14-29-108_me weishu exp](https://user-images.githubusercontent.com/21967105/131792431-f1788409-153a-40f7-bed0-0f2efccd7ada.jpg)
![Screenshot_2021-09-02-14-14-15-403_k btrg](https://user-images.githubusercontent.com/21967105/131792450-4e36f5bf-237b-4268-95a6-44cdfb61e36d.jpg)
已经将Ed卸载。重启后单独在太极里面激活，结果还是已激活模块，系统服务未运行。
手机：红米K40，安卓11，miui12.5.6.0
另外：在我原来小米6，安卓10上是可以正常运行的，最近刚换的K40。
都是为了农行😂

**Comment by 96998a** [comment]
我按你的试一下。国内访问的速度，心都碎了😭

**Comment by 96998a** [comment]
![Screenshot_2021-09-02-15-40-59-170_org lsposed manager](https://user-images.githubusercontent.com/21967105/131803212-b6f5c004-8aa7-46bb-9cc2-e86d3c1f72fc.jpg)
![Screenshot_2021-09-02-15-41-15-430_k btrg](https://user-images.githubusercontent.com/21967105/131803251-3e97562f-0a95-4dc3-bba7-730e410179d4.jpg)
![Screenshot_2021-09-02-15-40-38-744_com tsng hidemyapplist](https://user-images.githubusercontent.com/21967105/131803294-399bac7a-fba9-40dc-b390-8599ca065006.jpg)
![Screenshot_2021-09-02-15-41-15-430_k btrg](https://user-images.githubusercontent.com/21967105/131803335-04c74a79-4c2d-492d-9340-a9395466ae1f.jpg)
![Screenshot_2021-09-02-15-40-08-873_com android bankabc](https://user-images.githubusercontent.com/21967105/131803365-f31a1169-c681-4190-8331-e831533e6bd8.jpg)
非常感谢你！
用lsposed终于可以正常打开了(已激活模块，系统服务运行)，不过面具里面安装过v26版本的riui了，软件还是显示magisk插件未安装。不过程序正常运行，我的大农行软件终于不再提示root导致强退了。
日志已截图给你。问题可能是出在太极上面，所以暂时只能用lsposd了

**Comment by Fe3O4-Git** [comment]
@96998a magisk插件需要单独安装
