### ISSUE TITLE
System service not running

### ISSUE THREAD

**Issue by xerta555** [Dr-TSNG/Hide-My-Applist#82]
Hi

I'm trying to install/use this module through Riru 26, i install it with Magisk enable the module in LSposed app, reboot and open HMA app, but it say me that the system service not running.

How can i fix it please?

thanks in advance.

**Comment by Dr-TSNG** [comment]
Uncheck and recheck the module in LSPosed, reboot

**Comment by xerta555** [comment]
> 
> 
> Uncheck and recheck the module in LSPosed, reboot

It works thanks.

I also note that I can't access the chat channel on Telegram, I've been automatically banned

**Comment by Dr-TSNG** [comment]
@xerta555 That is the comment group, not the discussion chat. The discussion chat invite link is hidden in pinned messages

**Comment by xerta555** [comment]
> That is the comment group, not the discussion chat. The discussion chat invite link is hidden in pinned messages

I don't see telegram link in the last pinned message, maybe in previous message?

**Comment by Dr-TSNG** [comment]
@xerta555

**Comment by xerta555** [comment]
> 
> 
> @xerta555 The first pinned message. You should find out how to decode yourself

Honestly i just see a message saying that the number of users who can join the group has been increased, but i don't see any more info in English

**Comment by Dr-TSNG** [comment]
@xerta555 Join the discussion group

₿58 (This is not bitcoin)
GTCx6Xsvc3wZmYcmScmixXR2HeikQJeyhvADrrCYMqUR4WnMqcoz

**Comment by xerta555** [comment]
> GTCx6Xsvc3wZmYcmScmixXR2HeikQJeyhvADrrCYMqUR4WnMqcoz

Ok, but i don't see what i'm supposed to do with that ^^ ?

**Comment by Dr-TSNG** [comment]
@xerta555 You need to figure out how to decode this by yourself

**Comment by xerta555** [comment]
> 
> 
> @xerta555 You need to figure out how to decode this by yourself

Not even the beginning of a solution?
Do all new users really have to play guessing games to get into this telegram group?

**Comment by Dr-TSNG** [comment]
@xerta555 Because a LOT of game cheaters joined before and made a big mess. The discussion group is for technical communications only.

**Comment by xerta555** [comment]
> 
> 
> @xerta555 Because a LOT of game cheaters joined before and made a big mess. The discussion group is for technical communications only.

I completely understand the approach, i just come in a way that is not virulent...

**Comment by Dr-TSNG** [comment]
@xerta555 The encode algorithm is base58, you can Google it. This comment will be deleted soon.

**Comment by xerta555** [comment]
> 
> 
> @xerta555 The encode algorithm is base58, you can Google it. This comment will be deleted soon.

Ok thanks i got it.
