### ISSUE TITLE
Magisk Extension Download

### ISSUE THREAD

**Issue by DavidBerdik** [Dr-TSNG/Hide-My-Applist#87]
I noticed that when the app is running, it says for me that a Magisk Extension is not installed. Where can I get the extension that it is referring to? I don't see one anywhere.

**Comment by cracky5322** [comment]
@DavidBerdik Hide My Applist
隐藏应用列表 Release / Beta 通道
https://t.me/HideMyApplist

**Comment by DavidBerdik** [comment]
So it's only available for beta? I am confused.

**Comment by cracky5322** [comment]
@DavidBerdik Release / Beta

**Comment by DavidBerdik** [comment]
Found it! I think this is the latest version, anyway.

https://t.me/HideMyApplist/61?single

**Comment by Dr-TSNG** [comment]
Check GitHub releases. Not every apk release bounds magisk extension. You may download it from previous releases, or find it on telegram channel.

**Comment by DavidBerdik** [comment]
@Dr-TSNG Thank you. I was not aware of this and it's what confused me.
