### ISSUE TITLE
能否考虑在黑名单模式下增加一个例外列表？

### ISSUE THREAD

**Issue by ficheny** [Dr-TSNG/Hide-My-Applist#88]
lataclysm虚拟定位模块需要对应用可见才能有效，但又想对其他应用隐藏。
一般情况下，只维护一个跟root，xp有关的模板，但又想对使用lataclysm虚拟定位的应用设置一个例外。
不知大佬能否考虑这个建议？

**Comment by Dr-TSNG** [comment]
逻辑过于复杂，不考虑
