### ISSUE TITLE
[Stuck Boot/BUG] Does Not Get Past The Boot Screen

### ISSUE THREAD

**Issue by George-Seven** [Dr-TSNG/Hide-My-Applist#92]
Release Tested - V2.2.1
Android Version - 10
Device - Redmi Note 9 Pro Max

Steps To Reproduce -
1) Install HideMyApplist-V2.2.1.apk

2) Install MagiskExtension-V0.7.zip via Magisk Manager

3) Reboot phone. Gets stuck in boot screen with the "Redmi" animation.
Does not bootloop, just permanently stuck in boot.

Used TWRP's file manager to delete the module and it booted normally. But of course, module not there.

**Comment by Dr-TSNG** [comment]
Try latest CI, uninstall magisk module first, and click the module status bar in app, install the new extension
